const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),ts=require('typescript'),vm=require('node:vm'),{DatabaseSync}=require('node:sqlite');
const cache=new Map(),mocks={};let providerFetch=async()=>{throw new Error("Unexpected external request")};
function load(file){file=path.resolve(file);if(cache.has(file))return cache.get(file).exports;const m={exports:{}};cache.set(file,m);const code=ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText;vm.runInNewContext(code,{exports:m.exports,module:m,Response,Request,URL,Date,console,AbortSignal,fetch:(...args)=>providerFetch(...args),require:n=>mocks[n]??(n.startsWith('@/')?load(n.slice(2)+'.ts'):n.startsWith('.')?load(path.resolve(path.dirname(file),n)+'.ts'):require(n))});return m.exports;}
const db=new DatabaseSync(':memory:');db.exec('CREATE TABLE user_training_data(user_id TEXT PRIMARY KEY,data TEXT,updated_at TEXT)');db.exec(fs.readFileSync('drizzle/0011_sloppy_randall.sql','utf8'));
const adapter={prepare(sql){let args=[];return {bind(...values){args=values;return this},async first(){return db.prepare(sql).get(...args)||null},async run(){return {meta:{changes:db.prepare(sql).run(...args).changes}}}}}};
mocks['@/app/chatgpt-auth']={getChatGPTUser:async r=>r.headers.get('x-test-user')?{email:r.headers.get('x-test-user'),displayName:'Test person'}:null};mocks['@/lib/account-scope']={accountScope:async(u,r)=>({id:u.email+(r.headers.get('x-test-mode')==='test'?':test':''),mode:'live'})};mocks['@/lib/admin-activity']={adminDatabase:()=>adapter};
const {emptyOnboarding,completeOnboarding,extractedProfile,hasExistingTraining}=load('lib/onboarding.ts'),{initialData}=load('lib/training.ts'),{planSchema}=load('lib/plan.ts'),route=load('app/api/onboarding/route.ts');
const request=(method,user,body,extra={})=>new Request('https://stride.test/api/onboarding',{method,headers:{origin:'https://stride.test',...(user?{'x-test-user':user}:{}),...extra},...(body?{body:JSON.stringify(body)}:{})});
const read=async(user,extra)=>{const r=await route.GET(request('GET',user,null,extra));return r.json()};
const put=async(user,body,extra)=>route.PUT(request('PUT',user,body,extra));
(async()=>{
 assert.equal((await route.GET(request('GET',null))).status,401);assert.equal((await put(null,{})).status,401);assert.equal((await put('a',{}, {origin:'https://evil.test'})).status,403);
 const blank=await read('beginner');assert.equal(blank.complete,false);assert.equal(blank.updatedAt,null);
 let draft=emptyOnboarding('Alex');draft.brief='New to lifting, dumbbells at home, twice weekly';draft.reply='I only have 30 minutes';
 let r=await put('beginner',{draft,baseUpdatedAt:null});assert.equal(r.status,200);let revision=(await r.json()).updatedAt;
 const resumed=await read('beginner');assert.equal(resumed.draft.brief,draft.brief);assert.equal(resumed.draft.reply,draft.reply);assert.equal(resumed.updatedAt,revision);assert.equal(db.prepare('SELECT count(*) AS n FROM user_training_data').get().n,0,'draft cannot create active training');
 assert.equal((await read('other')).draft.brief,'','account isolation');assert.equal((await read('beginner',{'x-test-mode':'test'})).draft.brief,'','test/live isolation');
 assert.equal((await put('beginner',{draft,baseUpdatedAt:null})).status,409,'stale device blocked');
 const plan=planSchema.parse({message:'Two short dumbbell sessions fit your stated schedule.',workouts:[{name:'First dumbbell session',description:'Keep the load comfortable.',entries:[{exerciseId:'e0',sets:2,reps:8,weight:null}]}],saveUpdates:{profile:[{field:'goal',value:'Build strength'},{field:'days',value:'2'},{field:'experience',value:'New to lifting'},{field:'equipment',value:'Dumbbells'}],goal:null,nutrition:null,measurement:null}});
 draft={...draft,profile:extractedProfile(draft.profile,plan),plan,stage:'review',messages:[{role:'user',content:draft.brief},{role:'assistant',content:plan.message}]};
 assert.equal(draft.profile.days,2);assert.equal(draft.profile.experience,'New to lifting');assert.equal(draft.profile.limitations,null);assert.equal(draft.profile.sex,null,'no sex inference');
 assert.equal((await put('beginner',{draft,baseUpdatedAt:revision,complete:true,acceptPlan:true})).status,400,'require reviewed body map');
 draft.profile.sex='Female';draft.plan.workouts[0].entries[0].sets=3;
 r=await put('beginner',{draft,baseUpdatedAt:revision,complete:true,acceptPlan:true});assert.equal(r.status,200);const saved=JSON.parse(db.prepare('SELECT data FROM user_training_data WHERE user_id=?').get('beginner').data);
 assert.equal(saved.profile.days,2);assert.equal(saved.templates[0].entries[0].sets,3);assert.equal(saved.coachPlanner.draft,false);assert.equal(saved.coachPlanner.ids[0],saved.templates[0].id);assert.equal(saved.workouts.length,0);assert.equal((await read('beginner')).complete,true);
 assert.equal((await put('beginner',{draft,baseUpdatedAt:null,complete:true,acceptPlan:true})).status,409,'no duplicated accepted plans');
 for(const mode of ['manual','coach','routine']){const d=emptyOnboarding();d.mode=mode;d.profile.sex='Male';const account=completeOnboarding(null,d,false);assert.equal(account.templates.length,0);assert.equal(account.profile.goal,null,'optional questions skipped');assert(hasExistingTraining(account));}
 const own=emptyOnboarding();own.mode='routine';own.profile.sex='Female';own.profile.experience='Experienced';own.plan=plan;own.plan.workouts[0].entries[0].weight=185;own.messages=[{role:'user',content:'Keep my existing bench routine'}];let accepted=completeOnboarding(null,own,true);assert.equal(accepted.templates[0].entries[0].weight,185);let declined=completeOnboarding(null,own,false);assert.equal(declined.templates.length,0);assert.equal(declined.coachPlanner.draft,true);assert.equal(declined.profile.experience,'Experienced');
 const existing=initialData();existing.workouts=[{id:'existing-session'}];assert.throws(()=>completeOnboarding(existing,own,true));db.prepare('INSERT INTO user_training_data VALUES(?,?,?)').run('existing',JSON.stringify(existing),'existing-revision');assert.equal((await read('existing')).complete,true);
 const invalid=structuredClone(own);invalid.plan.workouts[0].entries[0].exerciseId='invented';assert.throws(()=>completeOnboarding(null,invalid,true));
 mocks['cloudflare:workers']={env:{}};mocks['@/app/chatgpt-auth'].chatGPTSignInPath=()=>'/signin-with-chatgpt';mocks['@/lib/ai-connection']={resolveAIConnection:async()=>({apiKey:'test-only',shared:false,paid:false}),consumeSharedAllowance:async()=>true};mocks['@/lib/billing']={chargeAIUsage:async()=>{}};mocks['@/lib/server-profile']={getCoachContext:async()=>null};mocks['@/lib/admin-activity'].recordActivity=async()=>{};
 let aiRequest;providerFetch=async(url,options)=>{assert.equal(url,'https://api.openai.com/v1/responses');aiRequest=JSON.parse(options.body);return Response.json({status:'completed',output:[{content:[{type:'output_text',text:JSON.stringify({...plan,workouts:[{...plan.workouts[0],entries:[{exerciseId:'0',sets:2,reps:8,weight:null}]}]})}]}]})};
 const aiRoute=load('app/api/plan/route.ts');const aiBody={onboarding:true,intakeProfile:draft.profile,messages:[{role:'user',content:'Build a first workout using my dumbbells'}],exercises:[{id:'e6',name:'Dumbbell Curl',category:'Arms'}],currentPlan:null};
 const aiResponse=await aiRoute.POST(request('POST','new-ai-user',aiBody));assert.equal(aiResponse.status,200,'first-run AI works before profile is saved');assert.equal((await aiResponse.json()).workouts[0].entries[0].exerciseId,'e6');assert(aiRequest.input.some(m=>typeof m.content==='string'&&m.content.includes('FIRST RUN:')));assert(aiRequest.input.some(m=>typeof m.content==='string'&&m.content.includes('Dumbbells')));assert.equal(aiRequest.store,false);
 assert.equal((await aiRoute.POST(request('POST','new-ai-user',{...aiBody,onboarding:false}))).status,403,'ordinary planner keeps profile guard');assert.equal((await aiRoute.POST(request('POST',null,aiBody))).status,401);
 console.log('PASS: onboarding auth/origin guards, draft-only saves, cross-device resume, stale revisions, live/test/account isolation, extraction validation, review edits, atomic plan acceptance, no duplicate completion, beginner/manual/skip/routine paths, existing-account protection.');
})().catch(e=>{console.error(e);process.exit(1)});
