'use client';
import {forwardRef,useEffect,useImperativeHandle,useRef,useState} from 'react';import {LogIn,LogOut,UserRound,Cloud,CloudOff} from 'lucide-react';import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';import {Data,initialData,migrateData} from '@/lib/training';
import {recoveryKeys,clearAcknowledgedRecovery} from '@/lib/recovery';
type Account={signedIn:boolean;isAdmin?:boolean;name?:string;email?:string;signInUrl?:string;signOutUrl?:string};
export type AccountSyncHandle={saveNow:(data:Data)=>Promise<boolean>};
export const AccountSync=forwardRef<AccountSyncHandle,{data:Data;onLoad:(data:Data)=>void}>(function AccountSync({data,onLoad},ref){const [hasBackup,setHasBackup]=useState(false);const [account,setAccount]=useState<Account|null>(null),[open,setOpen]=useState(false),[ready,setReady]=useState(false),[sync,setSync]=useState<'checking'|'synced'|'local'|'error'>('checking');const tabId=useRef(crypto.randomUUID());const recoveryPrefix='stride-unsynced:'+account?.email;const recoveryKey=recoveryPrefix+':'+tabId.current;const revision=useRef<string|null>(null),saved=useRef(''),blocked=useRef(false),flushRef=useRef<()=>Promise<void>>(async()=>{}),writeQueue=useRef<Promise<boolean>>(Promise.resolve(true));const hydrated=useRef(false),latest=useRef(data);latest.current=data;
 useEffect(()=>{fetch('/api/account',{cache:'no-store'}).then(r=>r.json()).then(body=>setAccount(body as Account)).catch(()=>{setAccount({signedIn:false});setSync('error')})},[]);
 useEffect(()=>{if(!account||hydrated.current)return;if(!account.signedIn){setSync('error');return}hydrated.current=true;setSync('checking');fetch('/api/training-data',{cache:'no-store'}).then(async r=>{const body=await r.json() as {data?:Data;updatedAt?:string;resetAt?:string};if(!r.ok)throw new Error();if(body.data&&!body.resetAt&&(!Array.isArray(body.data.exercises)||!Array.isArray(body.data.workouts)||!Array.isArray(body.data.templates)))throw new Error('Invalid saved training data');const loaded=body.data&&!body.resetAt?migrateData(body.data):initialData();revision.current=body.updatedAt??null;saved.current=JSON.stringify(loaded);setHasBackup(recoveryKeys(localStorage,recoveryPrefix).length>0);onLoad(loaded);setSync('synced');setReady(true)}).catch(()=>setSync('error'))},[account,onLoad]);
 async function persist(snapshot:string){if(!account?.signedIn||!ready||blocked.current)return false;if(snapshot===saved.current)return true;setSync('checking');try{localStorage.setItem(recoveryKey,snapshot);setHasBackup(true);const response=await fetch('/api/training-data',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({data:JSON.parse(snapshot),baseUpdatedAt:revision.current})});const body=await response.json() as {updatedAt?:string};if(response.status===409)blocked.current=true;if(!response.ok||!body.updatedAt)throw new Error();revision.current=body.updatedAt;saved.current=snapshot;setHasBackup(clearAcknowledgedRecovery(localStorage,recoveryKey,recoveryPrefix));setSync('synced');return true}catch{setSync('error');return false}}
 function enqueue(snapshot:string){const task=writeQueue.current.then(()=>persist(snapshot),()=>persist(snapshot));writeQueue.current=task;return task}
 async function flush(){if(!account?.signedIn||!ready||blocked.current)return;const snapshot=JSON.stringify(latest.current);const ok=await enqueue(snapshot);if(ok&&!blocked.current&&saved.current===snapshot&&JSON.stringify(latest.current)!==snapshot)await flushRef.current()}
 flushRef.current=flush;
 useImperativeHandle(ref,()=>({saveNow:(next:Data)=>enqueue(JSON.stringify(next))}));
 useEffect(()=>{if(!ready)return;if(JSON.stringify(data)!==saved.current){try{localStorage.setItem(recoveryKey,JSON.stringify(data));setHasBackup(true)}catch{setSync('error')}}void flushRef.current()},[data,ready,account]);
 useEffect(()=>{const retry=()=>void flushRef.current();window.addEventListener('online',retry);return()=>window.removeEventListener('online',retry)},[]);

 function downloadBackup(){const copies=recoveryKeys(localStorage,recoveryPrefix).map(k=>({copy:k,data:JSON.parse(localStorage.getItem(k)||'null')}));if(!copies.length)return;const backup=JSON.stringify({copies},null,2);const url=URL.createObjectURL(new Blob([backup],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download='stride-unsynced-training.json';a.click();URL.revokeObjectURL(url)}
 useEffect(()=>{const warn=(event:BeforeUnloadEvent)=>{if(ready&&JSON.stringify(latest.current)!==saved.current){event.preventDefault();event.returnValue=''}};window.addEventListener('beforeunload',warn);return()=>window.removeEventListener('beforeunload',warn)},[ready]);
 const initial=account?.name?.trim().charAt(0).toUpperCase()||'Y';return <>{!ready&&<div className="sync-loading-gate" role="status"><p>{sync==='error'?'Your account data could not be loaded. Reload to try again.':'Loading your saved training…'}</p></div>}{ready&&hasBackup&&sync!=='checking'&&<div className="notice">An unsynced training copy is available on this device.<button className="text-button" onClick={downloadBackup}>Download recovery copy</button></div>}{ready&&sync==='error'&&<div className="notice" role="alert">{blocked.current?'Another session saved newer data. Your changes are kept on this device and have not overwritten it.':'Changes have not synced. They are kept on this device.'}{!blocked.current&&<button className="text-button" onClick={()=>void flush()}>Retry sync</button>}</div>}<button className="account-button" aria-label="Account" onClick={()=>setOpen(true)}>{account?.signedIn?initial:<UserRound size={18}/>}</button><Dialog open={open} onOpenChange={setOpen}><DialogContent className="app-dialog account-dialog"><DialogHeader><DialogTitle>{account?.signedIn?'Your Stride account':'Sign in to Stride'}</DialogTitle><DialogDescription>{account?.signedIn?'Your training is synced to your account. The site owner can view usage and workout activity.':'Your session has expired. Sign in again to continue using Stride.'}</DialogDescription></DialogHeader>{account?.signedIn?<><div className="account-profile"><span>{initial}</span><div><strong>{account.name}</strong><p>{account.email}</p></div></div><div className={'sync-status '+sync}>{sync==='synced'?<Cloud size={17}/>:sync==='error'?<CloudOff size={17}/>:<Cloud size={17}/>} {sync==='synced'?'Training synced':sync==='checking'?'Syncing training…':sync==='error'?'Sync unavailable — changes remain on this device':'Saved on this device'}</div>{account.isAdmin&&<a className="secondary full" href="/admin">Admin · Users & activity</a>}<a className="secondary full" href={account.signOutUrl} target="_top" onClick={()=>localStorage.removeItem('stride-v1')}><LogOut size={17}/> Log out</a></>:<a className="primary full" href={account?.signInUrl||'/signin-with-chatgpt?return_to=%2F'} target="_top"><LogIn size={17}/> Sign in with ChatGPT</a>}</DialogContent></Dialog></>});
