'use client';
import {useEffect,useMemo,useState} from 'react';
import {recentActivities} from '@/lib/daily-logging';
import {Activity,Plus,Pencil,Trash2} from 'lucide-react';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import type {Data} from '@/lib/training';
import {uid} from '@/lib/training';
import {localDay} from '@/lib/nutrition';
import {ActivityIntensity,ActivityLog,ActivityTemplate,activeCaloriesForDay,bestKnownWeight,emptyActivityEnergy,estimateActivityCalories} from '@/lib/activity-energy';

export function ActivityEnergy({data,onChange}:{data:Data;onChange:(next:Data)=>void}){
 const activity=data.activityEnergy||emptyActivityEnergy(),today=localDay();
 const [expanded,setExpanded]=useState(!!data.activityEnergy),[day,setDay]=useState(today),[template,setTemplate]=useState<ActivityTemplate|null>(null),[editingTemplate,setEditingTemplate]=useState<ActivityTemplate|null|undefined>(undefined),[editingLog,setEditingLog]=useState<ActivityLog|null>(null);
 const recents=recentActivities(activity.logs);
 const totals=activeCaloriesForDay(data,day),logs=activity.logs.filter(x=>x.date===day);
 function saveActivity(next:typeof activity){onChange({...data,activityEnergy:next})}
 function openLog(source:ActivityTemplate){setTemplate(source);setEditingLog({id:uid(),templateId:source.id,name:source.name,date:day,durationMinutes:source.durationMinutes,intensity:source.intensity,met:source.met,caloriesBurned:0,calorieSource:'estimate',energyWeightLb:bestKnownWeight(data,day),notes:''})}
 return <section id="activity-log" className="panel activity-energy"><div className="section-head"><div><h2><Activity size={19}/> Activity & energy</h2><p>Strength workouts and everything else you do, in one place.</p></div><button className="secondary" aria-expanded={expanded} onClick={()=>setExpanded(!expanded)}>{expanded?'Collapse':data.activityEnergy?'Open log':'Track activity'}</button></div>{expanded&&<div className="activity-energy-body">
  <div className="nutrition-toolbar"><label>Day<input type="date" max={today} value={day} onChange={e=>e.target.value&&setDay(e.target.value)}/></label>{day!==today&&<button className="text-button" onClick={()=>setDay(today)}>Back to today</button>}</div>
  <div className="activity-summary"><div><span>Active calories</span><strong>{totals.total.toLocaleString()} <small>kcal</small></strong></div><div><span>Strength</span><b>{totals.strength.toLocaleString()} kcal</b></div><div><span>Other activity</span><b>{totals.other.toLocaleString()} kcal</b></div></div>
  <p className="form-help">Exercise estimates only—not resting metabolism or total daily expenditure.</p>
  <div className="activity-heading"><div><h3>Quick log</h3><p>Tap a saved activity, then adjust today’s details if needed.</p></div><button className="primary" onClick={()=>{setTemplate(null);setEditingLog({id:uid(),name:'',date:day,durationMinutes:60,intensity:'Moderate',met:5,caloriesBurned:0,calorieSource:'estimate',energyWeightLb:bestKnownWeight(data,day),notes:''})}}><Plus size={16}/> Log activity</button></div>
  {recents.length>0&&<div className="activity-template-list" aria-label="Recent activities">{recents.map(x=><button className="secondary" key={x.id} onClick={()=>{setTemplate(null);setEditingLog({...x,id:uid(),date:day})}}>Repeat {x.name} · {x.durationMinutes} min · {x.intensity}</button>)}</div>}<details><summary>Reusable activities</summary><button className="secondary" onClick={()=>setEditingTemplate(null)}>Create reusable activity</button>{activity.templates.length?<div className="activity-template-list">{activity.templates.map(x=><div className="activity-template" key={x.id}><button onClick={()=>openLog(x)}><strong>{x.name}</strong><span>{x.durationMinutes} min · {x.intensity}{x.scheduleHint?` · ${x.scheduleHint}`:''}</span></button><button className="icon-button" aria-label={`Edit ${x.name}`} onClick={()=>setEditingTemplate(x)}><Pencil size={16}/></button></div>)}</div>:<div className="nutrition-empty">No saved activities yet. Create one for a class, sport, walk, or any movement you want to reuse.</div>}</details>
  <div className="activity-day-log"><h3>{day===today?"Today’s activity":'Activity log'}</h3>{logs.length?logs.map(x=><div className="nutrition-entry" key={x.id}><div><strong>{x.name}</strong><p>{x.durationMinutes} min · {x.caloriesBurned} kcal · {x.intensity}</p></div><button className="icon-button" aria-label={`Edit ${x.name} log`} onClick={()=>{setTemplate(activity.templates.find(t=>t.id===x.templateId)||null);setEditingLog(x)}}><Pencil size={16}/></button><button className="icon-button" aria-label={`Delete ${x.name} log`} onClick={()=>saveActivity({...activity,logs:activity.logs.filter(a=>a.id!==x.id)})}><Trash2 size={16}/></button></div>):<p className="nutrition-empty">No other activity logged for this day.</p>}</div>

 </div>}
 <ActivityTemplateDialog value={editingTemplate} open={editingTemplate!==undefined} onClose={()=>setEditingTemplate(undefined)} onSave={next=>{saveActivity({...activity,templates:activity.templates.some(x=>x.id===next.id)?activity.templates.map(x=>x.id===next.id?next:x):[...activity.templates,next]});setEditingTemplate(undefined)}} onDelete={editingTemplate?()=>{saveActivity({...activity,templates:activity.templates.filter(x=>x.id!==editingTemplate.id)});setEditingTemplate(undefined)}:undefined}/>
 <ActivityLogDialog value={editingLog} template={template} data={data} open={!!editingLog} onClose={()=>setEditingLog(null)} onSave={next=>{saveActivity({...activity,logs:activity.logs.some(x=>x.id===next.id)?activity.logs.map(x=>x.id===next.id?next:x):[...activity.logs,next]});setDay(next.date);setEditingLog(null)}}/>
 </section>
}

function ActivityTemplateDialog({value,open,onClose,onSave,onDelete}:{value:ActivityTemplate|null|undefined;open:boolean;onClose:()=>void;onSave:(v:ActivityTemplate)=>void;onDelete?:()=>void}){
 return <Dialog open={open} onOpenChange={x=>{if(!x)onClose()}}><DialogContent className="app-dialog"><DialogHeader><DialogTitle>{value?'Edit activity':'Create reusable activity'}</DialogTitle><DialogDescription>Set a typical duration and effort. You can adjust both every time you log it.</DialogDescription></DialogHeader><form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);onSave({id:value?.id||uid(),name:String(f.get('name')).trim(),description:String(f.get('description')).trim(),durationMinutes:Number(f.get('duration')),intensity:String(f.get('intensity')) as ActivityIntensity,met:Number(f.get('met')),scheduleHint:String(f.get('schedule')).trim()})}}><label>Activity name<input name="name" required maxLength={80} defaultValue={value?.name} placeholder="Walk, class, practice…"/></label><label>Short description <input name="description" maxLength={200} defaultValue={value?.description}/></label><div className="form-grid"><label>Typical minutes<input name="duration" type="number" inputMode="decimal" min={5} max={720} required defaultValue={value?.durationMinutes||60}/></label><label>Usual effort<select name="intensity" defaultValue={value?.intensity||'Moderate'}><option>Light</option><option>Moderate</option><option>Vigorous</option></select></label></div><details><summary>Calorie estimate & other details</summary><div className="form-grid"><label>Energy intensity (MET)<input name="met" type="number" inputMode="decimal" min={1.5} max={18} step={0.1} required defaultValue={value?.met||5}/></label><label>Schedule note (optional)<input name="schedule" maxLength={80} defaultValue={value?.scheduleHint} placeholder="e.g. Mondays"/></label></div><p className="form-help">MET controls the estimate. If you’re unsure, ask the coach to create the activity from your description.</p></details><button className="primary full">Save activity</button>{onDelete&&<button type="button" className="text-button full" onClick={onDelete}>Delete activity</button>}</form></DialogContent></Dialog>
}

function ActivityLogDialog({value,template,data,open,onClose,onSave}:{value:ActivityLog|null;template:ActivityTemplate|null;data:Data;open:boolean;onClose:()=>void;onSave:(v:ActivityLog)=>void}){
 const [duration,setDuration]=useState(''),[weight,setWeight]=useState(''),[intensity,setIntensity]=useState<ActivityIntensity>('Moderate'),[calories,setCalories]=useState(''),[manual,setManual]=useState(false);
 useEffect(()=>{if(value){setDuration(String(value.durationMinutes));setWeight(value.energyWeightLb?String(value.energyWeightLb):String(bestKnownWeight(data,value.date)||''));setIntensity(value.intensity);setCalories(value.caloriesBurned?String(value.caloriesBurned):'');setManual(value.calorieSource==='manual')}},[value]);
 const baseMet=template?.met??value?.met??5,baseIntensity=template?.intensity??value?.intensity??'Moderate',factor={Light:.78,Moderate:1,Vigorous:1.25}[intensity]/{Light:.78,Moderate:1,Vigorous:1.25}[baseIntensity],met=Math.max(1.5,Math.min(18,Math.round(baseMet*factor*10)/10)),estimate=useMemo(()=>estimateActivityCalories(Number(weight),Number(duration),met),[weight,duration,met]);
 if(!value)return null;
 return <Dialog open={open} onOpenChange={x=>{if(!x)onClose()}}><DialogContent className="app-dialog"><DialogHeader><DialogTitle>{data.activityEnergy?.logs.some(x=>x.id===value.id)?"Edit activity":value.name?`Log ${value.name}`:"Log activity"}</DialogTitle><DialogDescription>Adjust what happened today. The estimate uses duration, body weight, and activity intensity.</DialogDescription></DialogHeader><form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget),finalCalories=manual?Number(calories):estimate;if(!finalCalories)return;onSave({...value,name:String(f.get('name')).trim(),date:String(f.get('date')),durationMinutes:Number(duration),intensity,met,energyWeightLb:Number(weight),caloriesBurned:finalCalories,calorieSource:manual?'manual':'estimate',notes:String(f.get('notes')).trim()})}}><label>Activity name<input name="name" required maxLength={80} defaultValue={value.name} placeholder="Jiu-Jitsu, walk, class…"/></label><label>Date<input name="date" type="date" required max={localDay()} defaultValue={value.date}/></label><div className="form-grid"><label>Minutes<input type="number" inputMode="decimal" min={5} max={720} required value={duration} onChange={e=>setDuration(e.target.value)}/></label></div><label>Effort<select value={intensity} onChange={e=>setIntensity(e.target.value as ActivityIntensity)}><option>Light</option><option>Moderate</option><option>Vigorous</option></select></label><details open={!weight}><summary>Calories & body weight</summary><label>Body weight · lb<input type="number" inputMode="decimal" min={50} max={1000} step={0.1} required value={weight} placeholder="Required for estimate" onChange={e=>setWeight(e.target.value)}/></label><div className="activity-estimate"><span>Estimated activity calories</span><strong>{estimate?`${estimate} kcal`:'Add body weight'}</strong></div><label className="check-row"><input type="checkbox" checked={manual} onChange={e=>{setManual(e.target.checked);if(e.target.checked&&!calories)setCalories(String(estimate||''))}}/> Enter a different calorie value</label>{manual&&<label>Calories burned<input type="number" inputMode="decimal" min={1} max={10000} required value={calories} onChange={e=>setCalories(e.target.value)}/></label>}</details><label>Notes (optional)<input name="notes" defaultValue={value.notes}/></label><button className="primary full" disabled={!manual&&!estimate}>{data.activityEnergy?.logs.some(x=>x.id===value.id)?"Save changes":"Add activity"}</button></form></DialogContent></Dialog>
}
