import {AdminHourlyActivityChart} from '@/components/admin-hourly-activity-chart';
type Report={
 summary:{visits:number;guest_entry_views:number;engaged:number;trial_starts:number;signups:number;avg_seconds:number;avg_scroll:number};
 events:Array<{event_type:string;target:string|null;count:number}>;
 sources:Array<{source:string;visits:number;trials:number;signups:number}>;
 daily:Array<{day:string;visits:number;trials:number;signups:number}>;
 geography:Array<{country:string;region:string|null;visits:number;trials:number;signups:number}>;
 hourly:Array<{hour:number;active_users:number}>;
};
const areaNames:Record<string,string>={overview:'Overview',workouts:'Workouts',progress:'Progress',logs:'Logs',library:'Library'};
const clickNames:Record<string,string>={auth_email_request:'Email sign-in requested',auth_email_verify:'Email code verified',auth_google:'Google sign-in selected',auth_try_guest:'Guest option selected',landing_sign_in:'Sign-in link selected',hero_try_free:'Hero · Try Stride free',footer_try_free:'Footer · Try Stride free',account_menu:'Account menu opened',account_create:'Account creation started'};
const eventName=(value:string,target:string|null)=>value==='page_view'?`${target==='guest'?'Guest entry':target==='app'?'Guest app':target==='auth'?'Account sign-in':'Landing'} page views`:value==='try_guest'?'Guest trials started':value==='account_created'?'Accounts created':value==='click'?target?.startsWith('area_')?`Opened ${areaNames[target.slice(5)]||target.slice(5)}`:target?.startsWith('dialog_')?`Opened ${target.slice(7).replaceAll('_',' ')}`:target?.startsWith('logs_')?`Opened Logs · ${target.slice(5)}`:clickNames[target||'']||`Button or link · ${target||'other'}`:value==='scroll'?`Scroll depth · ${target||''}%`:'Other interaction';
export function AdminLandingAnalytics({report}:{report:Report}){
 const {summary}=report;
 return <>
  <section className="admin-section-heading"><h2>Visitor activity · last 30 days</h2><p>Anonymous visits, active time, interface areas used, geography, and the path to trying Stride or creating an account.</p></section>
  <div className="landing-analytics-metrics"><article><strong>{summary.visits}</strong><span>Visits</span></article><article><strong>{summary.guest_entry_views}</strong><span>/guest page views</span></article><article><strong>{summary.engaged}</strong><span>Engaged visits</span></article><article><strong>{summary.avg_seconds}s</strong><span>Average active time</span></article><article><strong>{summary.avg_scroll}%</strong><span>Average scroll depth</span></article><article><strong>{summary.trial_starts}</strong><span>Guest trials started</span></article><article><strong>{summary.signups}</strong><span>Accounts created</span></article></div>
  {!summary.visits&&<p className="notice">No visits have been recorded yet. This report will fill in as visitors use the updated landing page.</p>}
  <section className="landing-analytics-grid">
   <article className="panel"><h3>Where visitors came from</h3>{report.sources.length?<div className="landing-report-table"><div className="landing-report-row landing-report-head"><span>Campaign or source</span><b>Visits</b><b>Trials</b><b>Accounts</b></div>{report.sources.map(row=><div className="landing-report-row" key={row.source}><span>{row.source}</span><b>{row.visits}</b><b>{row.trials}</b><b>{row.signups}</b></div>)}</div>:<p>No source data yet.</p>}</article>
   <article className="panel"><h3>Visitor geography</h3>{report.geography.length?<div className="landing-report-table"><div className="landing-report-row landing-report-head"><span>Country / region</span><b>Visits</b><b>Trials</b><b>Accounts</b></div>{report.geography.map(row=><div className="landing-report-row" key={`${row.country}-${row.region||''}`}><span>{row.country}{row.region?` · ${row.region}`:''}</span><b>{row.visits}</b><b>{row.trials}</b><b>{row.signups}</b></div>)}</div>:<p>No location data supplied by the hosting platform yet.</p>}</article>
   <article className="panel"><h3>What people clicked</h3>{report.events.filter(row=>row.event_type==='click'||row.event_type==='scroll').length?<div className="landing-report-table">{report.events.filter(row=>row.event_type==='click'||row.event_type==='scroll').map(row=><div className="landing-report-row" key={row.event_type+'-'+row.target}><span>{eventName(row.event_type,row.target)}</span><b>{row.count}</b></div>)}</div>:<p>No button clicks or scroll activity recorded yet.</p>}</article>
   <article className="panel"><h3>Active users by hour · today</h3><p>Unique anonymous sessions with activity in each New York local-time hour.</p><AdminHourlyActivityChart data={report.hourly}/>{!report.hourly.some(row=>row.active_users>0)&&<p>No hourly activity recorded yet.</p>}</article>
   <article className="panel"><h3>Visits by day</h3>{report.daily.length?<div className="landing-report-table">{report.daily.map(row=><div className="landing-report-row" key={row.day}><span>{new Date(row.day+'T12:00:00Z').toLocaleDateString('en-US',{month:'short',day:'numeric',timeZone:'UTC'})}</span><b>{row.visits} visits</b><b>{row.trials} trials</b><b>{row.signups} accounts</b></div>)}</div>:<p>No daily data yet.</p>}</article>
   <article className="panel"><h3>Most common events</h3>{report.events.length?<div className="landing-report-table">{report.events.filter(row=>!['click','scroll'].includes(row.event_type)).map(row=><div className="landing-report-row" key={row.event_type+'-'+row.target}><span>{eventName(row.event_type,row.target)}</span><b>{row.count}</b></div>)}</div>:<p>No tracked events yet.</p>}</article>
  </section>
  <p className="form-help">Visits use a random first-party session ID. No IP address, email, workout content, or page text is stored in this report. Geography is limited to country and broad region supplied by the hosting platform; no city or precise location is collected. A guest trial is linked to its guest account ID so you can label it in Users. UTM campaign names and a yes/no Google Ads click-tag indicator help group visits by source; raw ad click IDs are not stored. Data older than 180 days is cleared when new visits arrive.</p>
 </>;
}
