import {AdminHourlyActivityChart} from '@/components/admin-hourly-activity-chart';
type Report={
 summary:{visits:number;google_ads_visits:number;guest_entry_views:number;engaged:number;trial_starts:number;signups:number;avg_seconds:number;avg_scroll:number};
 events:Array<{event_type:string;target:string|null;count:number;users:number}>;
 sources:Array<{source:string;visits:number;trials:number;signups:number;avg_seconds:number;setup_views:number;coach_requests:number;workouts_started:number;workouts_completed:number}>;
 daily:Array<{day:string;visits:number;trials:number;signups:number}>;
 geography:Array<{country:string;region:string|null;visits:number;trials:number;signups:number}>;
 hourly:Array<{hour:number;active_users:number}>;
 funnel:Array<{stage:string;users:number;conversion:number|null}>;
 screenTimes:Array<{target:string|null;visits:number;users:number;avg_seconds:number;total_seconds:number}>;
 lastActions:Array<{event_type:string;target:string|null;users:number;avg_seconds:number}>;
 retention:{eligible1:number;returned1:number;rate1:number;eligible7:number;returned7:number;rate7:number};
 warnings:string[];
};
const areaNames:Record<string,string>={overview:'Overview',workouts:'Workouts',progress:'Progress',logs:'Logs',library:'Library'};
const clickNames:Record<string,string>={auth_email_request:'Email sign-in requested',auth_email_verify:'Email code verified',auth_google:'Google sign-in selected',auth_try_guest:'Guest option selected',landing_sign_in:'Sign-in link selected',hero_try_free:'Hero · Try Stride free',footer_try_free:'Footer · Try Stride free',account_menu:'Account menu opened',account_create:'Account creation started',onboarding_start_logging:'Chose direct workout logging',onboarding_coach_requested:'Asked coach for a starting point',workout_started:'Started a workout',workout_first_set:'Logged a set',workout_completed:'Finished a workout'};
const eventName=(value:string,target:string|null)=>value==='page_view'?`${target==='guest'?'Guest entry':target==='app'?'Guest app':target==='auth'?'Account sign-in':'Landing'} page views`:value==='try_guest'?'Guest trials started':value==='account_created'?'Accounts created':value==='click'?target?.startsWith('area_')?`Opened ${areaNames[target.slice(5)]||target.slice(5)}`:target?.startsWith('dialog_')?`Opened ${target.slice(7).replaceAll('_',' ')}`:target?.startsWith('logs_')?`Opened Logs · ${target.slice(5)}`:clickNames[target||'']||`Button or link · ${target||'other'}`:value==='scroll'?`Scroll depth · ${target||''}%`:value==='page_time'?`Time on ${target==='app'?'the app':target==='onboarding'?'setup':target==='guest'?'guest entry':'the landing page'}`:'Other interaction';
export function AdminLandingAnalytics({report}:{report:Report}){
 const {summary}=report;
 return <>
  <section className="admin-section-heading"><h2>Visitor activity · last 30 days</h2><p>See which ad-tagged visitors start a guest account, what they do next, where activity stops, and whether they return.</p></section>
  <div className="landing-analytics-metrics"><article><strong>{summary.visits}</strong><span>Visits</span></article><article><strong>{summary.google_ads_visits}</strong><span>Google Ads-tagged visits</span></article><article><strong>{summary.guest_entry_views}</strong><span>/guest page views</span></article><article><strong>{summary.engaged}</strong><span>Engaged visits</span></article><article><strong>{summary.avg_seconds}s</strong><span>Average active time</span></article><article><strong>{summary.avg_scroll}%</strong><span>Average scroll depth</span></article><article><strong>{summary.trial_starts}</strong><span>Guest trials started</span></article><article><strong>{summary.signups}</strong><span>Accounts created</span></article></div>
  <section className="panel landing-funnel"><h3>New user activation · last 30 days</h3><p>Guest accounts moving from setup toward a completed first workout. Percentages compare each step with the prior step.</p><div className="landing-funnel-steps">{report.funnel.map((step,index)=><div className="landing-funnel-step" key={step.stage}><div className="landing-funnel-label"><span>{step.stage}</span><strong>{step.users}</strong><small>{index===0?'Starting point':step.conversion===null?'—':`${step.conversion}% of previous`}</small></div><div className="landing-funnel-track"><span style={{width:`${Math.max(step.users?4:0,report.funnel[0]?.users?Math.round(step.users/report.funnel[0].users*100):0)}%`}}/></div></div>)}</div><div className="landing-retention"><div><strong>{report.retention.rate1}%</strong><span>returned after 1+ day</span><small>{report.retention.returned1} of {report.retention.eligible1} guests old enough to measure</small></div><div><strong>{report.retention.rate7}%</strong><span>returned after 7+ days</span><small>{report.retention.returned7} of {report.retention.eligible7} guests old enough to measure</small></div></div><p className="form-help">A “first set” is the first recorded set action. Return rate counts guests active in Stride at least 1 or 7 days after starting; newer guests are excluded until they have had time to return.</p></section>
  {!summary.visits&&<p className="notice">No visits have been recorded yet. This report will fill in as visitors use the updated landing page.</p>}
  {report.warnings.length>0&&<p className="notice">Some aggregate metrics are unavailable: {report.warnings.join(', ')}. The rest of the report remains available.</p>}
  <section className="landing-analytics-grid">
   <article className="panel"><h3>Google Ads &amp; visit source</h3><p>Compare which sources bring guests who move into a workout. Google Ads-tagged visits count site sessions where an ad click tag reached Stride; they are not the Ads platform’s click count. Compare the same date range in both reports.</p>{report.sources.length?<div className="landing-source-list">{report.sources.map(row=><div className="landing-source-row" key={row.source}><strong>{row.source}</strong><span>{row.visits} visits · {row.trials} guest trials · {row.signups} accounts</span><small>{row.setup_views} setup views · {row.coach_requests} coach requests · {row.workouts_started} workouts started · {row.workouts_completed} completed · {row.avg_seconds}s average active time</small></div>)}</div>:<p>No source data yet.</p>}</article>
   <article className="panel"><h3>Visitor geography</h3>{report.geography.length?<div className="landing-report-table"><div className="landing-report-row landing-report-head"><span>Country / region</span><b>Visits</b><b>Trials</b><b>Accounts</b></div>{report.geography.map(row=><div className="landing-report-row" key={`${row.country}-${row.region||''}`}><span>{row.country}{row.region?` · ${row.region}`:''}</span><b>{row.visits}</b><b>{row.trials}</b><b>{row.signups}</b></div>)}</div>:<p>No location data supplied by the hosting platform yet.</p>}</article>
   <article className="panel"><h3>Guest actions and milestones</h3>{report.events.length?<div className="landing-report-table">{report.events.map(row=><div className="landing-report-row landing-action-row" key={row.event_type+'-'+row.target}><span>{eventName(row.event_type,row.target)}</span><b>{row.count} events<br/><small>{row.users} guests</small></b></div>)}</div>:<p>No tracked activity yet.</p>}</article>
   <article className="panel"><h3>Where guest activity stopped</h3><p>Each guest appears once under their latest recorded screen or action.</p>{report.lastActions.length?<div className="landing-report-table">{report.lastActions.map(row=><div className="landing-report-row" key={row.event_type+'-'+row.target}><span>{eventName(row.event_type,row.target)}</span><b>{row.users} guests{row.avg_seconds?` · ${row.avg_seconds}s`:''}</b></div>)}</div>:<p>No guest activity yet.</p>}</article>
   <article className="panel"><h3>Time spent by screen</h3><p>Active time recorded while the page was visible.</p>{report.screenTimes.length?<div className="landing-report-table">{report.screenTimes.map(row=><div className="landing-report-row" key={row.target}><span>{eventName('page_time',row.target).replace('Time on ','')}</span><b>{row.avg_seconds}s avg · {row.users} guests</b></div>)}</div>:<p>No guest screen-time samples yet.</p>}</article>
   <article className="panel"><h3>Active users by hour · today</h3><p>Unique anonymous sessions with activity in each New York local-time hour.</p><AdminHourlyActivityChart data={report.hourly}/>{!report.hourly.some(row=>row.active_users>0)&&<p>No hourly activity recorded yet.</p>}</article>
   <article className="panel"><h3>Visits by day</h3>{report.daily.length?<div className="landing-report-table">{report.daily.map(row=><div className="landing-report-row" key={row.day}><span>{new Date(row.day+'T12:00:00Z').toLocaleDateString('en-US',{month:'short',day:'numeric',timeZone:'UTC'})}</span><b>{row.visits} visits</b><b>{row.trials} trials</b><b>{row.signups} accounts</b></div>)}</div>:<p>No daily data yet.</p>}</article>
   <article className="panel"><h3>Most common events</h3>{report.events.filter(row=>!['click','scroll','page_time'].includes(row.event_type)).length?<div className="landing-report-table">{report.events.filter(row=>!['click','scroll','page_time'].includes(row.event_type)).map(row=><div className="landing-report-row" key={row.event_type+'-'+row.target}><span>{eventName(row.event_type,row.target)}</span><b>{row.count}</b></div>)}</div>:<p>No tracked events yet.</p>}</article>
  </section>
  <p className="form-help">This report aggregates anonymous sessions and account-linked milestones. It records which screens and actions were used, time, and whether a workout was started, a set was logged, or a workout was finished; it never stores workout names, exercises, set values, field text, email, or IP address. Return rate is available only for guest accounts with at least 7 days of history. New activation milestones begin accumulating after this update. Data older than 180 days is cleared when new visits arrive.</p>
 </>;
}
