'use client';
import {useState} from 'react';
import {SlidersHorizontal} from 'lucide-react';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from './ui/dialog';
import {coachStyleNames,coachStyles,type CoachStyle,type CoachIntensity} from '@/lib/coach-style';
import {useCoachMemory} from './coach-memory';
import type {Data,Appearance} from '@/lib/training';
export function CoachStylePicker({style,intensity,onChange,disabled=false}:{style?:CoachStyle|null;intensity?:CoachIntensity|null;onChange:(style:CoachStyle,intensity:CoachIntensity)=>void;disabled?:boolean}){
 const chosen=style??'Calm Strategist',level=intensity??'Medium';
 return <div className="coach-style-picker"><label>Coaching style<select disabled={disabled} value={chosen} onChange={e=>onChange(e.target.value as CoachStyle,level)}>{coachStyleNames.map(name=><option key={name}>{name}</option>)}</select></label><p>{coachStyles[chosen].description}</p><div className="coach-style-sample"><span>VOICE PREVIEW · AFTER A MISSED SESSION</span><blockquote>{coachStyles[chosen].sample}</blockquote></div><label>How strongly should the personality come through?<select disabled={disabled} value={level} onChange={e=>onChange(chosen,e.target.value as CoachIntensity)}><option value="Low">Low · understated</option><option value="Medium">Medium · natural</option><option value="High">High · distinctive</option></select></label><small>This changes your coach’s voice, not your workout difficulty or targets. You can change it anytime.</small></div>;
}
export function CoachStyleSettings(){
 const {data,applyNow}=useCoachMemory('style');
 const [open,setOpen]=useState(false),[style,setStyle]=useState<CoachStyle>('Calm Strategist'),[intensity,setIntensity]=useState<CoachIntensity>('Medium'),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 function show(){setStyle(data.profile?.coachStyle??'Calm Strategist');setIntensity(data.profile?.coachIntensity??'Medium');setMessage('');setOpen(true)}
 async function save(){if(!data.profile||busy)return;setBusy(true);setMessage('');try{const saved=await applyNow('offer',{...data,profile:{...data.profile,coachStyle:style,coachIntensity:intensity}},'Coaching style');setMessage(saved?'Coaching style saved. Your next coach reply will use it.':'Your style was not saved. Please retry.')}catch{setMessage('Your style could not be saved. Please retry.')}finally{setBusy(false)}}
 return <><button className="text-button coach-style-trigger" onClick={show} aria-label="Change coaching style"><SlidersHorizontal size={17}/><span>Coach style</span></button><Dialog open={open} onOpenChange={value=>{if(!busy)setOpen(value)}}><DialogContent className="app-dialog"><DialogHeader><DialogTitle>Choose your coach’s voice</DialogTitle><DialogDescription>The same attention to your training, delivered your way.</DialogDescription></DialogHeader><CoachStylePicker style={style} intensity={intensity} disabled={busy} onChange={(s,i)=>{setStyle(s);setIntensity(i);setMessage('')}}/><button className="primary full" disabled={busy||!data.profile} onClick={()=>void save()}>{busy?'Saving…':'Save coaching style'}</button>{message&&<p role="status">{message}</p>}</DialogContent></Dialog></>;
}
const defaultAppearance:Appearance={colorMode:'light',density:'comfortable',homeTab:'Overview'};
export function PersonalizationSettings({data,onChange}:{data:Data;onChange:(next:Data)=>void}){
 const [open,setOpen]=useState(false);
 const appearance={...defaultAppearance,...data.appearance,colorMode:data.appearance?.colorMode??(data.dark?'dark':'light')};
 const update=(next:Partial<Appearance>)=>onChange({...data,dark:(next.colorMode??appearance.colorMode)==='dark',appearance:{...appearance,...next}});
 const updateCoach=(next:Partial<NonNullable<Data['profile']>>)=>data.profile&&onChange({...data,profile:{...data.profile,...next}});
 return <><button className="text-button personalize-trigger" onClick={()=>setOpen(true)} aria-label="Open personalization settings"><SlidersHorizontal size={17}/><span>Personalize</span></button><Dialog open={open} onOpenChange={setOpen}><DialogContent className="app-dialog personalization-dialog"><DialogHeader><DialogTitle>Make Stride yours</DialogTitle><DialogDescription>Choose how Stride looks, feels, and where it opens.</DialogDescription></DialogHeader><div className="personalization-options"><label>Color theme<select value={appearance.colorMode} onChange={e=>update({colorMode:e.target.value as Appearance['colorMode']})}><option value="light">Light</option><option value="dark">Dark</option><option value="system">Match device</option></select></label><label>Layout density<select value={appearance.density} onChange={e=>update({density:e.target.value as Appearance['density']})}><option value="comfortable">Comfortable</option><option value="compact">Compact</option></select><small>Compact trims spacing so you can see more at once.</small></label><label>Open Stride to<select value={appearance.homeTab} onChange={e=>update({homeTab:e.target.value as Appearance['homeTab']})}>{(['Overview','Workouts','Progress','Logs','Library'] as const).map(tab=><option key={tab}>{tab}</option>)}</select></label>{data.profile&&<><hr/><label>Coaching style<select value={data.profile.coachStyle??'Calm Strategist'} onChange={e=>updateCoach({coachStyle:e.target.value as CoachStyle})}>{coachStyleNames.map(name=><option key={name}>{name}</option>)}</select></label><p>{coachStyles[data.profile.coachStyle??'Calm Strategist'].description}</p><label>Coach personality<select value={data.profile.coachIntensity??'Medium'} onChange={e=>updateCoach({coachIntensity:e.target.value as CoachIntensity})}><option value="Low">Low · understated</option><option value="Medium">Medium · natural</option><option value="High">High · distinctive</option></select></label></>}</div><button className="primary full" onClick={()=>setOpen(false)}>Done</button></DialogContent></Dialog></>;
}
