'use client';
import {useState} from 'react';
import {useCoachMemory} from './coach-memory';
import {applyProgressProposal} from '@/lib/plan';
import {profileSchema} from '@/lib/profile';
export function CoachSaveOffer({area}:{area:string}){const {offer,setOffer,data,change,setMessages}=useCoachMemory(area),[busy,setBusy]=useState(false),[error,setError]=useState('');if(!offer||!offer.profile.length&&!offer.goal&&!offer.nutrition)return null;
 async function save(){if(!offer||busy)return;setBusy(true);setError('');try{if(offer.goal?.kind==='strength'&&!data.exercises.some(e=>e.id===offer.goal?.exerciseId))throw new Error('Ask your coach to select an existing exercise for this goal.');let profile=data.profile;if(offer.profile.length){const patch=Object.fromEntries(offer.profile.map(p=>[p.field,p.field==='days'||p.field==='minutes'?Number(p.value):p.value]));profile=profileSchema.parse({...data.profile,...patch});}
 change(current=>({...applyProgressProposal(current,{goal:offer.goal,nutrition:offer.nutrition?{calorieTarget:offer.nutrition.calorieTarget??current.nutrition?.calorieTarget??null,proteinTarget:offer.nutrition.proteinTarget??current.nutrition?.proteinTarget??null}:null}),...(profile?{profile}:{}),coachOffers:{...current.coachOffers,[area]:null}}));setMessages(m=>[...m,{role:'assistant',content:'You confirmed these updates. The updates are queued for account sync. Check the sync status if you go offline.'}]);}catch(e){setError(e instanceof Error?e.message:'Could not save. Please retry.')}finally{setBusy(false)}}
 return <div className="session-proposal"><strong>Save this for future coaching?</strong>{offer.profile.map(p=><span key={p.field}>{p.field}: {p.value}</span>)}{offer.goal&&<span>Goal: {offer.goal.title} · {offer.goal.target} {offer.goal.unit}</span>}{offer.nutrition&&<span>Daily targets: {offer.nutrition.calorieTarget??'unchanged'} calories · {offer.nutrition.proteinTarget??'unchanged'} g protein</span>}<div className="button-group"><button className="primary" disabled={busy} onClick={()=>void save()}>{busy?'Saving…':'Save updates'}</button><button className="secondary" disabled={busy} onClick={()=>setOffer(null)}>Not now</button></div>{error&&<p role="alert" className="plan-error">{error}</p>}</div>
}
