'use client';
import type {Data} from '@/lib/training';
import type {PendingOperation} from '@/lib/account-operations';
const fieldName=(value:string)=>({templates:'Workout templates',workouts:'Workout',entries:'Exercises',sets:'Sets',reps:'Reps',weight:'Weight (lb)',baseWeight:'Starting weight (lb)',baseReps:'Starting reps',baseSets:'Starting sets',targetWeight:'Target weight (lb)',targetReps:'Target reps',exerciseId:'Exercise',bodyFat:'Body fat (%)',calorieTarget:'Daily base calories',proteinTarget:'Daily protein (g)',carbTarget:'Daily carbs (g)',fatTarget:'Daily fat (g)',activityCalorieAdjustment:'Activity calories added (%)',durationMinutes:'Duration (minutes)',scheduleHint:'Schedule',strengthProfile:'Body weight context',bodyMeasurements:'Measurements',activityEnergy:'Activities'}[value]||value.replace(/([A-Z])/g,' $1').replace(/^./,c=>c.toUpperCase()));
function record(value:unknown):value is Record<string,unknown>{return !!value&&typeof value==='object'&&!Array.isArray(value)}
function ChangeValue({value,data}:{value:unknown;data:Data}):React.ReactNode{
 if(value===undefined)return <span>Remove record</span>;
 if(value===null)return <span>Not set</span>;
 if(Array.isArray(value))return <div className="change-list">{value.map((v,i)=><div key={i}><ChangeValue value={v} data={data}/></div>)}</div>;
 if(record(value)){
  if(typeof value.exerciseId==='string'&&typeof value.sets==='number')return <div className="change-exercise"><strong>{data.exercises.find(e=>e.id===value.exerciseId)?.name||'Exercise unavailable'}</strong><span>{value.sets} × {String(value.reps)} <span className="muted">· {Number(value.weight)>0?`${value.weight} lb`:'Choose load'}</span></span></div>;
  if(typeof value.name==='string'&&Array.isArray(value.entries))return <details className="change-workout"><summary><span><strong>{value.name}</strong><small>{value.entries.length} exercises{value.entries.every(e=>record(e)&&typeof e.sets==='number')?` · ${value.entries.reduce((n:number,e:Record<string,unknown>)=>n+Number(e.sets),0)} sets`:''}</small></span><span className="change-expand">Details</span></summary><div className="change-workout-body">{typeof value.description==='string'&&value.description&&<p>{value.description}</p>}<ChangeValue value={value.entries} data={data}/></div></details>;
  return <dl className="change-fields">{Object.entries(value).filter(([k])=>!['id','coachMessages'].includes(k)).map(([k,v])=><div key={k}><dt>{fieldName(k)}</dt><dd>{k==='exerciseId'?data.exercises.find(e=>e.id===v)?.name||'Exercise unavailable':<ChangeValue value={v} data={data}/>}</dd></div>)}</dl>;
 }
 return <span>{typeof value==='boolean'?(value?'Yes':'No'):String(value)}</span>;
}
export function CoachOperationCard({op,data,onApply,onDiscard,onView}:{op:PendingOperation;data:Data;onApply:(id:string)=>unknown;onDiscard:(id:string)=>unknown;onView?:(target:string)=>void}){
 const patches=op.payload.filter(p=>!p.path[0].startsWith('coach'));
 const plan=op.action==='plan';
 const title=plan?'Workout plan':op.label;
 return <article className="coach-operation"><header className="coach-operation-heading"><h3>{title}</h3><span className={'operation-status '+(op.receipt?'is-saved':'')} role="status">{op.status}</span></header><p className="operation-intro">{op.receipt?'These changes were saved to your account.':'Review the proposal, then apply it when you’re ready.'}</p><div className="operation-actions">{!op.receipt&&<button className="primary" disabled={op.status==='Saving'} onClick={()=>void onApply(op.id)}>{op.status==='Saving'?'Saving…':op.submitted?'Check save / retry':op.status==='Needs attention'?'Reapply reviewed changes':'Apply changes'}</button>}{op.receipt&&onView&&<button className="secondary" onClick={()=>onView(op.receipt!.targets[0]||'')}>View changes</button>}{(!op.submitted||op.receipt)&&<button className="text-button" disabled={op.status==='Saving'} onClick={()=>onDiscard(op.id)}>{op.receipt?'Dismiss':'Discard'}</button>}</div>{op.error&&<p className="plan-error" role="alert">{op.error}</p>}<div className="operation-changes">{patches.map((p,i)=>{const fullWorkout=record(p.after)&&Array.isArray(p.after.entries)&&typeof p.after.name==='string';return <div key={i} className={fullWorkout?'':'change-item'}>{!fullWorkout&&<h4>{p.path.filter(x=>!x.startsWith('@')).map(fieldName).join(' · ')}</h4>}{!fullWorkout&&p.before!==undefined&&p.after!==undefined&&!record(p.before)&&!Array.isArray(p.before)&&<div className="change-before">Previously: <ChangeValue value={p.before} data={data}/></div>}<ChangeValue value={p.after} data={data}/></div>})}</div></article>
}
