'use client';
import {useEffect,useState} from 'react';
import {CircleHelp} from 'lucide-react';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import type {Exercise} from '@/lib/training';
export function ExerciseHelp({exercise}:{exercise:Exercise}){
 const [open,setOpen]=useState(false),[answer,setAnswer]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[attempt,setAttempt]=useState(0);
 useEffect(()=>{if(!open||answer)return;const controller=new AbortController();const timeout=setTimeout(()=>controller.abort(),65000);setBusy(true);setError('');
 fetch('/api/exercise-coach',{method:'POST',headers:{'Content-Type':'application/json'},signal:controller.signal,body:JSON.stringify({exercises:[{name:exercise.name,category:exercise.category,mode:exercise.mode}],messages:[{role:'user',content:`Explain how to do this exact exercise for a beginner: ${exercise.name} (${exercise.category}). Give a short plain-language description, equipment and setup, 3–5 numbered steps for one repetition, and 2 common mistakes to avoid. If the name is ambiguous, explain the ambiguity rather than guessing a variation. This is explanation only; do not propose or change any exercises or workouts.`}]})}).then(async r=>{const b=await r.json() as {message?:string;error?:string};if(!r.ok||!b.message)throw new Error(b.error||'Instructions could not be loaded.');if(!controller.signal.aborted)setAnswer(b.message)}).catch(e=>{if(!controller.signal.aborted)setError(e instanceof Error?e.message:'Instructions could not be loaded.');else setError('Instructions took too long. Please try again.')}).finally(()=>{clearTimeout(timeout);setBusy(false)});
 return()=>{clearTimeout(timeout);controller.abort()};
 },[open,answer,attempt,exercise.name,exercise.category,exercise.mode]);
 return <><button type="button" className="exercise-help-button" aria-label={`How to do ${exercise.name}`} onClick={()=>setOpen(true)}><span>{exercise.name}</span><CircleHelp size={17} aria-hidden="true"/></button><Dialog open={open} onOpenChange={setOpen}><DialogContent className="app-dialog exercise-help-dialog"><DialogHeader><DialogTitle>{exercise.name}</DialogTitle><DialogDescription>How to do this exercise</DialogDescription></DialogHeader>{busy&&<p role="status">Getting step-by-step instructions…</p>}{answer&&<div className="exercise-help-answer"><small>Stride coach explanation</small><p>{answer}</p></div>}{error&&<div><p className="plan-error" role="alert">{error}</p><button className="secondary" disabled={busy} onClick={()=>setAttempt(a=>a+1)}>Try again</button></div>}<a className="secondary" href={'https://www.youtube.com/results?search_query='+encodeURIComponent(exercise.name+' exercise proper form tutorial')} target="_blank" rel="noopener noreferrer">Find video examples ↗</a><p className="form-help">Video search opens YouTube. Check that the demonstration matches this exercise and equipment.</p></DialogContent></Dialog></>;
}
