'use client';
import {useEffect,useState} from 'react';
type Update={id:string;message:string;area:string;notified_at:string};
export function FeedbackUpdates(){
 const [items,setItems]=useState<Update[]>([]),[editing,setEditing]=useState<string|null>(null),[comment,setComment]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
 useEffect(()=>{let active=true;const load=async()=>{try{const r=await fetch('/api/feedback?mine=1',{cache:'no-store'});if(r.ok){const b=await r.json() as {items:Update[]};if(active)setItems(b.items)}}catch{}};void load();const timer=setInterval(()=>{if(document.visibilityState==='visible')void load()},60000);const focus=()=>void load();window.addEventListener('focus',focus);return()=>{active=false;clearInterval(timer);window.removeEventListener('focus',focus)}},[]);
 async function respond(item:Update,resolved:boolean){if(busy)return;setBusy(true);setError('');try{const r=await fetch('/api/feedback',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:item.id,action:resolved?'resolved':'unresolved',notifiedAt:item.notified_at,comment:resolved?'':comment})}),b=await r.json() as {error?:string};if(!r.ok)throw new Error(b.error);setItems(s=>s.filter(x=>x.id!==item.id));setEditing(null);setComment('');setNotice(resolved?'Thanks for confirming! Your request is resolved.':'Thanks. Your follow-up was sent to the owner and the request is back in the inbox.')}catch(e){setError(e instanceof Error?e.message:'Your response could not be saved. Please try again.')}finally{setBusy(false)}}
 if(!items.length&&!notice)return null;
 return <section className="panel feedback-updates" aria-label="Updates on your feedback"><h2>Your feedback helped improve Stride</h2>{notice&&<p role="status">{notice}</p>}{error&&<p className="plan-error" role="alert">{error}</p>}{items.map(item=><article key={item.id}><strong>A change has been applied to your request</strong><p className="feedback-text">{item.message}</p><p>Did this resolve the issue?</p>{editing===item.id?<form onSubmit={e=>{e.preventDefault();void respond(item,false)}}><label htmlFor="feedback-followup">What still isn’t working?</label><textarea id="feedback-followup" rows={3} maxLength={5000} required disabled={busy} value={comment} onChange={e=>setComment(e.target.value)} placeholder="Tell us what happens now and what you expected."/><div className="button-group"><button className="primary" disabled={busy||!comment.trim()}>{busy?'Sending…':'Send follow-up'}</button><button type="button" className="text-button" disabled={busy} onClick={()=>setEditing(null)}>Cancel</button></div></form>:<div className="button-group"><button className="primary" disabled={busy} onClick={()=>void respond(item,true)}>Yes, resolved</button><button className="secondary" disabled={busy} onClick={()=>{setEditing(item.id);setComment('');setError('')}}>Not resolved</button></div>}</article>)}{!items.length&&<button className="text-button" onClick={()=>setNotice('')}>Dismiss</button>}</section>;
}
