'use client';
import {useState} from 'react';
import {MessageSquare,Paperclip,X} from 'lucide-react';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {preparePhoto} from '@/lib/photo';
export function Feedback({area}:{area:string}){
 const [open,setOpen]=useState(false),[message,setMessage]=useState(''),[screenshots,setScreenshots]=useState<string[]>([]),[busy,setBusy]=useState(false),[preparing,setPreparing]=useState(false),[error,setError]=useState(''),[sent,setSent]=useState(false);
 async function attach(files:Iterable<File>|null){if(!files)return;const attachments=Array.from(files);if(!attachments.length)return;setError('');if(attachments.length+screenshots.length>3){setError('You can attach up to three screenshots.');return}setPreparing(true);try{const images=await Promise.all(attachments.map(preparePhoto));setScreenshots(s=>[...s,...images])}catch(e){setError(e instanceof Error?e.message:'Unable to attach screenshot.')}finally{setPreparing(false)}}
 async function send(){if(busy||preparing||!message.trim())return;setBusy(true);setError('');try{const response=await fetch('/api/feedback',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({message,area,screenshots})});const body=await response.json() as {error?:string};if(!response.ok)throw new Error(body.error||'Unable to send feedback.');setSent(true);setMessage('');setScreenshots([])}catch(e){setError(e instanceof Error?e.message:'Unable to send feedback.')}finally{setBusy(false)}}
 return <><button className="text-button" onClick={()=>{setOpen(true);setSent(false)}}><MessageSquare size={17}/> Feedback</button><Dialog open={open} onOpenChange={o=>{if(!busy&&!preparing)setOpen(o)}}><DialogContent className="app-dialog"><DialogHeader><DialogTitle>Share feedback</DialogTitle><DialogDescription>Report a problem or suggest an improvement. Your message and screenshots go to the Stride owner.</DialogDescription></DialogHeader>{sent?<div role="status"><p>Thanks! Your feedback has been sent.</p><button className="primary full" onClick={()=>setOpen(false)}>Done</button></div>:<form onSubmit={e=>{e.preventDefault();void send()}}><label htmlFor="feedback-message">What would you like us to know?</label><textarea id="feedback-message" rows={4} maxLength={5000} required value={message} disabled={busy} onChange={e=>setMessage(e.target.value)} onPaste={e=>{const images=Array.from(e.clipboardData.items).filter(item=>item.type.startsWith('image/')).map(item=>item.getAsFile()).filter((file):file is File=>!!file);if(images.length){e.preventDefault();void attach(images)}}} placeholder="What happened, or what would make Stride better?"/><label className="feedback-attach"><Paperclip size={16}/> Attach or paste screenshots (up to 3)<input type="file" accept="image/*" multiple disabled={busy||preparing} onChange={e=>{void attach(e.target.files);e.target.value=''}}/></label><div className="feedback-images">{screenshots.map((src,i)=><div key={i}><img src={src} alt={`Attached screenshot ${i+1}`}/><button type="button" className="icon-button" disabled={busy||preparing} aria-label={`Remove screenshot ${i+1}`} onClick={()=>setScreenshots(s=>s.filter((_,j)=>j!==i))}><X size={18}/></button></div>)}</div>{preparing&&<p role="status">Preparing screenshots…</p>}{error&&<p className="plan-error" role="alert">{error}</p>}<button className="primary full" disabled={busy||preparing||!message.trim()}>{busy?'Sending…':'Send feedback'}</button></form>}</DialogContent></Dialog></>;
}
