'use client';
import {useState} from 'react';
import {Target,Plus,Check} from 'lucide-react';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {Data,uid} from '@/lib/training';
import {Goal,goalProgress} from '@/lib/goals';
const today=()=>new Date().toLocaleDateString('en-CA');
const blank=():Goal=>({id:uid(),title:'',kind:'measurement',unit:'lb',start:0,target:0,started:today(),deadline:'',archived:false,checks:[]});
export function Goals({data,onChange}:{data:Data;onChange:(goals:Goal[])=>void}){
 const goals=data.goals||[],[draft,setDraft]=useState<Goal|null>(null),[check,setCheck]=useState<string|null>(null),[value,setValue]=useState(''),[note,setNote]=useState(''),[date,setDate]=useState(today()),[error,setError]=useState(''),[showArchived,setShowArchived]=useState(false);
 const put=(goal:Goal)=>onChange(goals.some(g=>g.id===goal.id)?goals.map(g=>g.id===goal.id?goal:g):[...goals,goal]);
 const visible=goals.filter(g=>showArchived||!g.archived);
 function preset(title:string,kind:Goal['kind'],unit:string){setDraft({...blank(),title,kind,unit,start:0,target:kind==='milestone'?1:0});setError('')}
 return <section className="panel goals-panel"><div className="section-head"><div><h2><Target size={19}/> Personal goals <span className="muted">Optional</span></h2><p>Track a target that matters to you.</p></div><button className="secondary" onClick={()=>{setDraft(blank());setError('')}}><Plus size={17}/> Add goal</button></div>{!goals.length?<div className="goal-intro"><p>Set a measurement, training habit, or milestone. No setup is required to keep using Stride.</p><div className="goal-presets"><button className="secondary" onClick={()=>preset('Lose fat — body-weight trend','measurement','lb')}>Body weight</button><button className="secondary" onClick={()=>preset('Waist measurement','measurement','in')}>Waist size</button><button className="secondary" onClick={()=>preset('Train consistently','sessions','workouts')}>Workout count</button><button className="secondary" onClick={()=>preset('My training milestone','milestone','')}>A milestone</button></div></div>:null}
 <div className="goal-list">{visible.map(g=>{const p=goalProgress(g,data),overdue=g.deadline&&g.deadline<today()&&!p.reached;return <article className="goal-card" key={g.id}><div className="goal-title"><h3>{g.title}</h3><button className="text-button" onClick={()=>{setDraft({...g});setError('')}}>Edit</button></div><div className="goal-reading"><strong>{g.kind==='milestone'?(p.reached?'Achieved':'In progress'):`${p.current} ${g.unit}`}</strong><span>{g.kind!=='milestone'&&`Target: ${g.target} ${g.unit}`}</span></div><progress max={100} value={p.percent} aria-label={`${g.title}: ${p.percent}% of target`}/><p>{p.reached?'Goal reached — well done!':overdue?'Target date passed. Review your progress or adjust the date.':g.deadline?`Target date: ${g.deadline}`:'No deadline set'}{g.archived?' · Archived':''}</p><details><summary>Details & check-ins</summary><p>Started {g.started}{g.kind==='measurement'?` at ${g.start} ${g.unit}`:''}</p>{g.kind==='sessions'?<p>Counts completed workouts dated within your goal period automatically.</p>:p.checks.length?p.checks.map(c=><div className="goal-check" key={c.id}><span>{c.date} · {g.kind==='milestone'?'Achieved':`${c.value} ${g.unit}`} {c.note&&`— ${c.note}`}</span><button className="text-button" onClick={()=>put({...g,checks:g.checks.filter(x=>x.id!==c.id)})} aria-label={`Remove check-in on ${c.date}`}>Remove</button></div>):<p>No check-ins yet.</p>}<button className="text-button" onClick={()=>put({...g,archived:!g.archived})}>{g.archived?'Restore goal':'Archive goal'}</button></details>{!g.archived&&g.kind!=='sessions'&&<button className="secondary" onClick={()=>{setCheck(g.id);setValue(g.kind==='milestone'?'1':'');setNote('');setDate(today());setError('')}}>{g.kind==='milestone'?<Check size={16}/>:<Plus size={16}/>} {g.kind==='milestone'?'Mark achieved':'Add check-in'}</button>}</article>})}</div>{goals.some(g=>g.archived)&&<button className="text-button archive-toggle" onClick={()=>setShowArchived(!showArchived)}>{showArchived?'Hide archived goals':'Show archived goals'}</button>}
 <Dialog open={!!draft} onOpenChange={open=>{if(!open)setDraft(null)}}><DialogContent className="app-dialog"><DialogHeader><DialogTitle>{goals.some(g=>g.id===draft?.id)?'Edit goal':'Set a personal goal'}</DialogTitle><DialogDescription>Choose how to measure progress. A deadline is optional.</DialogDescription></DialogHeader>{draft&&<form onSubmit={e=>{e.preventDefault();if(!draft.title.trim()||!Number.isFinite(draft.start)||!Number.isFinite(draft.target)||draft.kind!=='milestone'&&draft.start===draft.target){setError('Enter a title and a target different from your starting value.');return}if(draft.deadline&&draft.deadline<draft.started){setError('Choose a deadline on or after the start date.');return}put({...draft,title:draft.title.trim()});setDraft(null)}}><label>Goal name<input required maxLength={100} value={draft.title} onChange={e=>setDraft({...draft,title:e.target.value})} placeholder="For example: Reduce waist size"/></label><label>How to track<Select value={draft.kind} onValueChange={v=>setDraft({...draft,kind:v as Goal['kind'],start:0,target:v==='milestone'?1:0,unit:v==='sessions'?'workouts':v==='milestone'?'':draft.unit,checks:[]})} disabled={draft.checks.length>0}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="measurement">A measurement — manual check-ins</SelectItem><SelectItem value="sessions">Completed workouts — automatic</SelectItem><SelectItem value="milestone">A milestone — mark achieved</SelectItem></SelectContent></Select></label>{draft.kind==='measurement'&&<><p className="form-help">Body weight and waist size are ways to track change; they do not directly measure fat loss. Strength, repetitions, and other measurements can also be logged here.</p><label>Unit<input required maxLength={20} value={draft.unit} onChange={e=>setDraft({...draft,unit:e.target.value})} placeholder="lb, kg, inches, reps…"/></label></>}{draft.kind!=='milestone'&&<div className="form-grid">{draft.kind==='measurement'&&<label>Starting value<input required type="number" step="any" value={draft.start||''} onChange={e=>setDraft({...draft,start:Number(e.target.value)})}/></label>}<label>Target<input required type="number" min={draft.kind==='sessions'?1:undefined} step={draft.kind==='sessions'?1:'any'} value={draft.target||''} onChange={e=>setDraft({...draft,target:Number(e.target.value)})}/></label></div>}<div className="form-grid"><label>Start date<input required type="date" value={draft.started} onChange={e=>setDraft({...draft,started:e.target.value})}/></label><label>Target date (optional)<input type="date" min={draft.started} value={draft.deadline} onChange={e=>setDraft({...draft,deadline:e.target.value})}/></label></div>{error&&<p className="plan-error" role="alert">{error}</p>}<button className="primary full">Save goal</button></form>}</DialogContent></Dialog>
 <Dialog open={!!check} onOpenChange={open=>{if(!open)setCheck(null)}}><DialogContent className="app-dialog"><DialogHeader><DialogTitle>Add a check-in</DialogTitle><DialogDescription>{goals.find(g=>g.id===check)?.title}</DialogDescription></DialogHeader><form onSubmit={e=>{e.preventDefault();const g=goals.find(g=>g.id===check);if(!g)return;if(!value.trim()||!Number.isFinite(Number(value))||date<g.started||date>today()){setError('Enter a value and a date between the goal start and today.');return}put({...g,checks:[...g.checks,{id:uid(),date,value:Number(value),note:note.trim()}]});setCheck(null)}}>{goals.find(g=>g.id===check)?.kind!=='milestone'&&<label>Value ({goals.find(g=>g.id===check)?.unit})<input required type="number" step="any" value={value} onChange={e=>setValue(e.target.value)}/></label>}<label>Date<input required type="date" max={today()} min={goals.find(g=>g.id===check)?.started} value={date} onChange={e=>setDate(e.target.value)}/></label><label>Note (optional)<input maxLength={300} value={note} onChange={e=>setNote(e.target.value)}/></label>{error&&<p className="plan-error" role="alert">{error}</p>}<button className="primary full">Save check-in</button></form></DialogContent></Dialog>
 </section>
}
