'use client';
import {useState} from 'react';
import {Plus,Utensils,Settings2,Pencil,Trash2,RotateCcw,ArrowRight,Droplets} from 'lucide-react';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Nutrition,FoodLog,ActivityCalorieAdjustment,emptyNutrition,localDay,nutritionTotals,recentFoods,calorieBudget,hydrationTotal} from '@/lib/nutrition';
import {uid} from '@/lib/training';
import type {Workout} from '@/lib/training';
import {workoutCaloriesForDay} from '@/lib/workout-energy';
import type {ActivityLog} from '@/lib/activity-energy';
import {activityCaloriesForDay} from '@/lib/activity-energy';

type EntryMode='food'|'total';

export function NutritionTracker({value,workouts,activityLogs,onChange}:{value?:Nutrition;workouts?:Workout[];activityLogs?:ActivityLog[];onChange:(n:Nutrition)=>void}){
 const data=value||emptyNutrition();
 const [expanded,setExpanded]=useState(!!value),[day,setDay]=useState(localDay()),[editing,setEditing]=useState<FoodLog|null>(null),[mode,setMode]=useState<EntryMode>('food'),[name,setName]=useState(''),[calories,setCalories]=useState(''),[protein,setProtein]=useState(''),[carbs,setCarbs]=useState(''),[fat,setFat]=useState(''),[activityAdjustment,setActivityAdjustment]=useState<ActivityCalorieAdjustment>(0),[entryDate,setEntryDate]=useState(localDay()),[settings,setSettings]=useState(false),[calorieTarget,setCalorieTarget]=useState(''),[proteinTarget,setProteinTarget]=useState(''),[carbTarget,setCarbTarget]=useState(''),[fatTarget,setFatTarget]=useState(''),[hydrationTarget,setHydrationTarget]=useState(''),[waterAmount,setWaterAmount]=useState('16'),[error,setError]=useState(''),[removed,setRemoved]=useState<FoodLog|null>(null),[added,setAdded]=useState<FoodLog|null>(null);
 const totals=nutritionTotals(data.entries,day),strengthCalories=workoutCaloriesForDay(workouts,day),otherCalories=activityCaloriesForDay(activityLogs,day),exerciseCalories=strengthCalories+otherCalories,entries=data.entries.filter(e=>e.date===day),days=[...new Set(data.entries.map(e=>e.date))].sort().reverse(),recents=recentFoods(data.entries),today=localDay();
 const {percent:activityPercent,adjustment:activityCaloriesAdded,budget:calorieTargetToday}=calorieBudget(data,exerciseCalories);
 const hydration=data.hydration||{dailyTargetOz:null,entries:[]},waterToday=hydrationTotal(data,day);
 function addWater(ounces:number){if(!Number.isFinite(ounces)||ounces<=0||ounces>300){setError('Enter between 1 and 300 fluid ounces.');return}setError('');onChange({...data,hydration:{...hydration,entries:[...hydration.entries,{id:uid(),date:day,ounces:Math.round(ounces*10)/10}]}})}

 function openEntry(entry?:FoodLog,nextMode:EntryMode='food'){
  if(!entry&&nextMode==='total')entry=data.entries.find(e=>e.date===day&&/^daily total(?: ·.*)?$/i.test(e.name));
  const draft=entry||{id:uid(),date:day,name:nextMode==='total'?'Daily total':'',calories:null,protein:null,carbs:null,fat:null};
  setMode(entry?.name.trim().toLocaleLowerCase().startsWith('daily total')?'total':nextMode);setEditing(draft);setName(draft.name);setCalories(draft.calories==null?'':String(draft.calories));setProtein(draft.protein==null?'':String(draft.protein));setCarbs(draft.carbs==null?'':String(draft.carbs));setFat(draft.fat==null?'':String(draft.fat));setEntryDate(draft.date);setError('');
 }
 function addAgain(source:FoodLog){const entry={...source,id:uid(),date:day};onChange({...data,entries:[...data.entries,entry]});setAdded(entry);setRemoved(null)}
 const parse=(v:string)=>v.trim()===''?null:Number(v),valid=(n:number|null)=>n===null||Number.isFinite(n)&&n>=0;
 const calorieCopy=calorieTargetToday===null?'No daily target set':totals.calories<calorieTargetToday?`${Math.round(calorieTargetToday-totals.calories).toLocaleString()} kcal remaining`:totals.calories===calorieTargetToday?'Today’s budget reached':`${Math.round(totals.calories-calorieTargetToday).toLocaleString()} kcal over today’s budget`;

 return <section id="nutrition-log" className="panel nutrition-panel"><div className="section-head"><div><h2><Utensils size={19}/> Nutrition & hydration <span className="muted">Optional</span></h2><p>Log food, daily totals, or water—only what is useful to you.</p></div><button className="secondary" aria-expanded={expanded} onClick={()=>setExpanded(!expanded)}>{expanded?'Collapse':value?'Open log':'Track food or water'}</button></div>{expanded&&<div className="nutrition-body">
  <div className="nutrition-toolbar"><label>Day<input type="date" value={day} max={today} onChange={e=>{if(e.target.value)setDay(e.target.value)}}/></label>{day!==today&&<button className="text-button" onClick={()=>setDay(today)}>Back to today</button>}<button className="secondary" onClick={()=>{setCalorieTarget(data.calorieTarget===null?'':String(data.calorieTarget));setProteinTarget(data.proteinTarget===null?'':String(data.proteinTarget));setCarbTarget(data.carbTarget==null?'':String(data.carbTarget));setFatTarget(data.fatTarget==null?'':String(data.fatTarget));setHydrationTarget(hydration.dailyTargetOz===null?'':String(hydration.dailyTargetOz));setActivityAdjustment(data.activityCalorieAdjustment===50||data.activityCalorieAdjustment===100?data.activityCalorieAdjustment:0);setError('');setSettings(true)}}><Settings2 size={16}/> Daily targets</button></div>
  <div className={'nutrition-totals '+(data.carbTarget!=null&&data.fatTarget!=null?'all-macros':'')}><div className="nutrition-total nutrition-total-primary"><span>Calories eaten</span><strong>{totals.calories.toLocaleString()} <small>kcal</small></strong>{calorieTargetToday!==null&&<progress max={calorieTargetToday} value={Math.min(totals.calories,calorieTargetToday)} aria-label={`Calories: ${totals.calories} of today's ${calorieTargetToday} calorie budget`}/>}<p>{calorieCopy}{calorieTargetToday!==null&&` · ${calorieTargetToday.toLocaleString()} today`}</p>{data.calorieTarget!==null&&activityCaloriesAdded>0&&<p className="nutrition-budget-detail">{data.calorieTarget.toLocaleString()} base + {activityCaloriesAdded.toLocaleString()} from activity</p>}{totals.missingCalories&&<p>Partial total: an entry has no calories.</p>}</div><MacroTotal label="Protein" value={totals.protein} target={data.proteinTarget}/>{data.carbTarget!=null&&<MacroTotal label="Carbohydrates" value={totals.carbs} target={data.carbTarget}/>} {data.fatTarget!=null&&<MacroTotal label="Fat" value={totals.fat} target={data.fatTarget}/>}</div>
  <div className="nutrition-exercise-burn"><span><strong>{exerciseCalories.toLocaleString()} kcal</strong> active calories</span><small>{exerciseCalories?`${strengthCalories} strength + ${otherCalories} other${activityPercent?` · ${activityCaloriesAdded.toLocaleString()} added to today’s budget (${activityPercent}%)`:' · Not added to today’s budget'} · Exercise estimate.`:'Finish a workout or log another activity to add exercise calories.'}</small></div>
  <section className="hydration-card"><div className="hydration-heading"><div><h3><Droplets size={18}/> Hydration <span className="muted">Optional</span></h3><p><strong>{waterToday.toLocaleString()} fl oz</strong>{hydration.dailyTargetOz!==null?` of ${hydration.dailyTargetOz.toLocaleString()} today`:' logged today'}</p></div>{hydration.dailyTargetOz!==null&&<progress max={hydration.dailyTargetOz} value={Math.min(waterToday,hydration.dailyTargetOz)} aria-label={`Hydration: ${waterToday} of ${hydration.dailyTargetOz} fluid ounces`}/>}</div><div className="hydration-quick" aria-label="Quick add water">{[8,12,16,24].map(oz=><button className="secondary" key={oz} onClick={()=>addWater(oz)}>+ {oz} oz</button>)}</div><form className="hydration-custom" onSubmit={e=>{e.preventDefault();addWater(Number(waterAmount))}}><label>Other amount · fl oz<input type="number" inputMode="decimal" min="1" max="300" step="any" value={waterAmount} onChange={e=>setWaterAmount(e.target.value)}/></label><button className="secondary">Add water</button></form>{hydration.entries.some(e=>e.date===day)&&<details><summary>Water entries</summary>{hydration.entries.filter(e=>e.date===day).map(e=><div className="nutrition-entry" key={e.id}><div><strong>{e.ounces} fl oz</strong></div><button className="icon-button" aria-label={`Delete ${e.ounces} fluid ounce water entry`} onClick={()=>onChange({...data,hydration:{...hydration,entries:hydration.entries.filter(x=>x.id!==e.id)}})}><Trash2 size={16}/></button></div>)}</details>}{error&&<p role="alert" className="plan-error">{error}</p>}</section>
  <p className="logging-coverage">{entries.length===1&&/^daily total(?: ·.*)?$/i.test(entries[0].name)&&entries[0].calories!==null&&entries[0].protein!==null&&(data.carbTarget==null||entries[0].carbs!=null)&&(data.fatTarget==null||entries[0].fat!=null)?'Full-day total entered':entries.length?'Partial log · foods entered do not confirm a complete day':'No food logged for this day'}</p><div className="nutrition-actions"><button className="primary" onClick={()=>openEntry(undefined,'food')}><Plus size={17}/> Log food or meal</button><button className="secondary" onClick={()=>openEntry(undefined,'total')}>{entries.some(e=>/^daily total(?: ·.*)?$/i.test(e.name))?"Edit daily total":"Enter daily total"} <ArrowRight size={16}/></button></div>
  {recents.length>0&&<div className="nutrition-recent"><div><strong>Have it again</strong><span>One tap adds it to {day===today?'today':'this day'}.</span></div><div className="nutrition-recent-list">{recents.map(item=><button key={`${item.id}-${item.calories}-${item.protein}-${item.carbs}-${item.fat}`} onClick={()=>addAgain(item)}><RotateCcw size={15}/><span><strong>{item.name}</strong><small>{item.calories===null?'—':`${item.calories} kcal`} · {item.protein===null?'—':`${item.protein} g protein`}{data.carbTarget!=null&&` · ${item.carbs??'—'} g carbs`}{data.fatTarget!=null&&` · ${item.fat??'—'} g fat`}</small></span></button>)}</div></div>}
  <p className="nutrition-help">Use “Enter daily total” if another app already has your numbers. Don’t also log the same foods here. Calories stay independent from macro estimates because labels can differ through rounding, fiber, and sugar alcohols.</p>
  <div className="nutrition-entries"><h3>{day===today?"Today’s log":'Food log'}</h3>{entries.length?entries.map(e=><div className="nutrition-entry" key={e.id}><div><strong>{e.name||'Quick entry'}</strong><p>{e.calories===null?'Calories not entered':`${e.calories} kcal`} · {e.protein===null?'Protein not entered':`${e.protein} g protein`}{data.carbTarget!=null&&` · ${e.carbs??'—'} g carbs`}{data.fatTarget!=null&&` · ${e.fat??'—'} g fat`}</p></div><button className="icon-button" aria-label={`Edit ${e.name||'entry'}`} onClick={()=>openEntry(e)}><Pencil size={16}/></button><button className="icon-button" aria-label={`Delete ${e.name||'entry'}`} onClick={()=>{setRemoved(e);setAdded(null);onChange({...data,entries:data.entries.filter(x=>x.id!==e.id)})}}><Trash2 size={16}/></button></div>):<p className="nutrition-empty">Nothing logged for this day yet.</p>}</div>
  {added&&<div className="nutrition-undo" role="status"><span><strong>{added.name}</strong> entered. Account sync is shown above.</span><button className="text-button" onClick={()=>{onChange({...data,entries:data.entries.filter(e=>e.id!==added.id)});setAdded(null)}}>Undo</button></div>}{removed&&<div className="nutrition-undo" role="status">Entry removed.<button className="text-button" onClick={()=>{if(!data.entries.some(e=>e.id===removed.id))onChange({...data,entries:[...data.entries,removed]});setRemoved(null)}}>Undo</button></div>}
  <details className="nutrition-history"><summary>Daily history</summary><p>Totals reflect logged entries, not necessarily full days.</p>{days.slice(0,30).map(date=>{const t=nutritionTotals(data.entries,date);return <button className="nutrition-day" key={date} onClick={()=>setDay(date)}><strong>{date}</strong><span>{t.calories} kcal · {t.protein} g protein{t.missingCalories||t.missingProtein?' · Partial':''}</span></button>})}{!days.length&&<p>Your daily totals will appear here after your first entry.</p>}<p>Showing the latest 30 logged days. Use the date picker to open any earlier day.</p></details>
 </div>}
 <Dialog open={!!editing} onOpenChange={open=>{if(!open)setEditing(null)}}><DialogContent className="app-dialog"><DialogHeader><DialogTitle>{data.entries.some(e=>e.id===editing?.id)?'Edit nutrition entry':mode==='total'?'Enter daily total':'Log food or meal'}</DialogTitle><DialogDescription>{mode==='total'?'Copy your daily totals from another tracker. This does not connect or sync that app.':'Add the portion you ate. Only the fields you track are required.'}</DialogDescription></DialogHeader><form onSubmit={e=>{e.preventDefault();if(!editing)return;const c=parse(calories),p=parse(protein),carb=parse(carbs),f=parse(fat);if(!valid(c)||!valid(p)||!valid(carb)||!valid(f)||c===null&&p===null&&carb===null&&f===null||!entryDate||entryDate>today){setError('Enter at least one nonnegative nutrition value, and choose today or an earlier date.');return}const entry={...editing,date:entryDate,name:name.trim(),calories:c,protein:p,carbs:carb,fat:f};onChange({...data,entries:data.entries.some(x=>x.id===entry.id)?data.entries.map(x=>x.id===entry.id?entry:x):[...data.entries,entry]});setDay(entryDate);setEditing(null);setAdded(null)}}>{mode==='total'&&data.entries.some(e=>e.date===entryDate&&e.id!==editing?.id)&&<p className="nutrition-warning">Other entries exist for this date. Remove overlapping foods or totals to avoid double-counting.</p>}{mode==='food'?<label>Food or meal name <input autoFocus value={name} maxLength={100} placeholder="Chicken bowl, protein shake…" onChange={e=>setName(e.target.value)}/></label>:<input type="hidden" value={name} readOnly/>}<div className="form-grid nutrition-macro-fields"><label>Calories<input autoFocus={mode==='total'} type="number" min={0} step="any" inputMode="decimal" value={calories} placeholder="Optional" onChange={e=>setCalories(e.target.value)}/></label><label>Protein (g)<input type="number" min={0} step="any" inputMode="decimal" value={protein} placeholder="Optional" onChange={e=>setProtein(e.target.value)}/></label>{data.carbTarget!=null&&<label>Carbs (g)<input type="number" min={0} step="any" inputMode="decimal" value={carbs} placeholder="Optional" onChange={e=>setCarbs(e.target.value)}/></label>}{data.fatTarget!=null&&<label>Fat (g)<input type="number" min={0} step="any" inputMode="decimal" value={fat} placeholder="Optional" onChange={e=>setFat(e.target.value)}/></label>}</div><label>Date<input required type="date" max={today} value={entryDate} onChange={e=>setEntryDate(e.target.value)}/></label>{error&&<p role="alert" className="plan-error">{error}</p>}<button className="primary full">{data.entries.some(e=>e.id===editing?.id)?'Save changes':entryDate===today?'Add to today':'Add entry'}</button></form></DialogContent></Dialog>
 <Dialog open={settings} onOpenChange={setSettings}><DialogContent className="app-dialog"><DialogHeader><DialogTitle>Daily targets</DialogTitle><DialogDescription>Every target is optional. Track only what helps you.</DialogDescription></DialogHeader><form onSubmit={e=>{e.preventDefault();const c=parse(calorieTarget),p=parse(proteinTarget),carb=parse(carbTarget),f=parse(fatTarget),water=parse(hydrationTarget);if(!valid(c)||!valid(p)||!valid(carb)||!valid(f)||!valid(water)||[c,p,carb,f,water].some(x=>x===0)||(carb===null)!==(f===null)||water!==null&&(water<8||water>400)){setError('Targets must be greater than zero. Hydration must be 8–400 fl oz. Enter both carbohydrate and fat targets for the complete macro view, or leave both blank.');return}onChange({...data,calorieTarget:c,proteinTarget:p,carbTarget:carb,fatTarget:f,activityCalorieAdjustment:activityAdjustment,hydration:{...hydration,dailyTargetOz:water}});setSettings(false)}}><label>Base calories per day<input type="number" min={1} step="any" value={calorieTarget} onChange={e=>setCalorieTarget(e.target.value)} placeholder="Optional"/></label><label>Protein per day (g)<input type="number" min={1} step="any" value={proteinTarget} onChange={e=>setProteinTarget(e.target.value)} placeholder="Optional"/></label><details><summary>Track all macros</summary><p className="form-help">Set both targets to add carbohydrates and fat to logging and the Overview visualization.</p><div className="form-grid"><label>Carbohydrates per day (g)<input type="number" min={1} step="any" value={carbTarget} onChange={e=>setCarbTarget(e.target.value)} placeholder="Optional"/></label><label>Fat per day (g)<input type="number" min={1} step="any" value={fatTarget} onChange={e=>setFatTarget(e.target.value)} placeholder="Optional"/></label></div></details><label>Hydration per day (fl oz)<input type="number" inputMode="decimal" min="8" max="400" step="any" value={hydrationTarget} onChange={e=>setHydrationTarget(e.target.value)} placeholder="Optional"/></label><label>Adjust calories on active days<select value={activityAdjustment} onChange={e=>setActivityAdjustment(Number(e.target.value) as ActivityCalorieAdjustment)}><option value={0}>Don’t add exercise calories</option><option value={50}>Add half of exercise calories</option><option value={100}>Add all exercise calories</option></select></label><p className="form-help"><strong>Which should I use?</strong> Choose “Don’t add” if your base target already includes your usual training. Half provides a conservative adjustment for uncertain estimates. Add all only when your base target excludes exercise and you trust the estimate.</p>{error&&<p className="plan-error" role="alert">{error}</p>}<button className="primary full">Save targets</button></form></DialogContent></Dialog>
 </section>;
}
function MacroTotal({label,value,target}:{label:string;value:number;target:number|null}){const remaining=target===null?null:Math.max(0,Math.round((target-value)*10)/10);return <div className="nutrition-total"><span>{label}</span><strong>{value.toLocaleString()} <small>g</small></strong>{target!==null&&<progress max={target} value={Math.min(value,target)} aria-label={`${label}: ${value} of ${target} grams`}/>}<p>{target===null?'No daily target set':remaining?`${remaining} g remaining · ${target} target`:value===target?'Daily target reached':`${Math.round((value-target)*10)/10} g over target`}</p></div>}
