'use client';
import {useState} from 'react';
import {Plus,Utensils,Settings2,Pencil,Trash2,RotateCcw,ArrowRight} from 'lucide-react';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Nutrition,FoodLog,emptyNutrition,localDay,nutritionTotals,recentFoods} from '@/lib/nutrition';
import {uid} from '@/lib/training';
import type {Workout} from '@/lib/training';
import {workoutCaloriesForDay} from '@/lib/workout-energy';

type EntryMode='food'|'total';

export function NutritionTracker({value,workouts,onChange}:{value?:Nutrition;workouts?:Workout[];onChange:(n:Nutrition)=>void}){
 const data=value||emptyNutrition();
 const [expanded,setExpanded]=useState(!!value),[day,setDay]=useState(localDay()),[editing,setEditing]=useState<FoodLog|null>(null),[mode,setMode]=useState<EntryMode>('food'),[name,setName]=useState(''),[calories,setCalories]=useState(''),[protein,setProtein]=useState(''),[entryDate,setEntryDate]=useState(localDay()),[settings,setSettings]=useState(false),[calorieTarget,setCalorieTarget]=useState(''),[proteinTarget,setProteinTarget]=useState(''),[error,setError]=useState(''),[removed,setRemoved]=useState<FoodLog|null>(null),[added,setAdded]=useState<FoodLog|null>(null);
 const totals=nutritionTotals(data.entries,day),exerciseCalories=workoutCaloriesForDay(workouts,day),entries=data.entries.filter(e=>e.date===day),days=[...new Set(data.entries.map(e=>e.date))].sort().reverse(),recents=recentFoods(data.entries),today=localDay();

 function openEntry(entry?:FoodLog,nextMode:EntryMode='food'){
  const draft=entry||{id:uid(),date:day,name:nextMode==='total'?'Daily total':'',calories:null,protein:null};
  setMode(entry?.name.trim().toLocaleLowerCase().startsWith('daily total')?'total':nextMode);setEditing(draft);setName(draft.name);setCalories(draft.calories===null?'':String(draft.calories));setProtein(draft.protein===null?'':String(draft.protein));setEntryDate(draft.date);setError('');
 }
 function addAgain(source:FoodLog){const entry={...source,id:uid(),date:day};onChange({...data,entries:[...data.entries,entry]});setAdded(entry);setRemoved(null)}
 const parse=(v:string)=>v.trim()===''?null:Number(v),valid=(n:number|null)=>n===null||Number.isFinite(n)&&n>=0;
 const calorieCopy=data.calorieTarget===null?'No daily target set':totals.calories<data.calorieTarget?`${Math.round(data.calorieTarget-totals.calories).toLocaleString()} kcal remaining`:totals.calories===data.calorieTarget?'Daily target reached':`${Math.round(totals.calories-data.calorieTarget).toLocaleString()} kcal over target`;

 return <section className="panel nutrition-panel"><div className="section-head"><div><h2><Utensils size={19}/> Nutrition <span className="muted">Optional</span></h2><p>Log meals quickly and stay on top of your daily intake.</p></div><button className="secondary" aria-expanded={expanded} onClick={()=>setExpanded(!expanded)}>{expanded?'Collapse':value?'Open log':'Track nutrition'}</button></div>{expanded&&<div className="nutrition-body">
  <div className="nutrition-toolbar"><label>Day<input type="date" value={day} max={today} onChange={e=>{if(e.target.value)setDay(e.target.value)}}/></label>{day!==today&&<button className="text-button" onClick={()=>setDay(today)}>Back to today</button>}<button className="secondary" onClick={()=>{setCalorieTarget(data.calorieTarget===null?'':String(data.calorieTarget));setProteinTarget(data.proteinTarget===null?'':String(data.proteinTarget));setError('');setSettings(true)}}><Settings2 size={16}/> Daily targets</button></div>
  <div className="nutrition-totals"><div className="nutrition-total nutrition-total-primary"><span>Calories eaten</span><strong>{totals.calories.toLocaleString()} <small>kcal</small></strong>{data.calorieTarget!==null&&<progress max={data.calorieTarget} value={Math.min(totals.calories,data.calorieTarget)} aria-label={`Calories: ${totals.calories} of ${data.calorieTarget}`}/>}<p>{calorieCopy}{data.calorieTarget!==null&&` · ${data.calorieTarget.toLocaleString()} target`}</p>{totals.missingCalories&&<p>Partial total: an entry has no calories.</p>}</div><div className="nutrition-total"><span>Protein</span><strong>{totals.protein.toLocaleString()} <small>g</small></strong>{data.proteinTarget!==null&&<progress max={data.proteinTarget} value={Math.min(totals.protein,data.proteinTarget)} aria-label={`Protein: ${totals.protein} of ${data.proteinTarget}`}/>}<p>{data.proteinTarget===null?'No daily target set':totals.protein<data.proteinTarget?`${Math.round((data.proteinTarget-totals.protein)*10)/10} g remaining · ${data.proteinTarget} target`:totals.protein===data.proteinTarget?'Daily target reached':`${Math.round((totals.protein-data.proteinTarget)*10)/10} g over target`}</p>{totals.missingProtein&&<p>Partial total: an entry has no protein.</p>}</div></div>
  <div className="nutrition-exercise-burn"><span><strong>{exerciseCalories.toLocaleString()} kcal</strong> burned in Stride workouts</span><small>{exerciseCalories?'Exercise estimate—not total daily expenditure.':'Finish a workout to add its estimated exercise calories.'}</small></div>
  <div className="nutrition-actions"><button className="primary" onClick={()=>openEntry(undefined,'food')}><Plus size={17}/> Log food or meal</button><button className="secondary" onClick={()=>openEntry(undefined,'total')}>Enter daily total <ArrowRight size={16}/></button></div>
  {recents.length>0&&<div className="nutrition-recent"><div><strong>Have it again</strong><span>One tap adds it to {day===today?'today':'this day'}.</span></div><div className="nutrition-recent-list">{recents.map(item=><button key={`${item.id}-${item.calories}-${item.protein}`} onClick={()=>addAgain(item)}><RotateCcw size={15}/><span><strong>{item.name}</strong><small>{item.calories===null?'—':`${item.calories} kcal`} · {item.protein===null?'—':`${item.protein} g protein`}</small></span></button>)}</div></div>}
  <p className="nutrition-help">Use “Enter daily total” if another app already has your numbers. Don’t also log the same foods here.</p>
  <div className="nutrition-entries"><h3>{day===today?"Today’s log":'Food log'}</h3>{entries.length?entries.map(e=><div className="nutrition-entry" key={e.id}><div><strong>{e.name||'Quick entry'}</strong><p>{e.calories===null?'Calories not entered':`${e.calories} kcal`} · {e.protein===null?'Protein not entered':`${e.protein} g protein`}</p></div><button className="icon-button" aria-label={`Edit ${e.name||'entry'}`} onClick={()=>openEntry(e)}><Pencil size={16}/></button><button className="icon-button" aria-label={`Delete ${e.name||'entry'}`} onClick={()=>{setRemoved(e);setAdded(null);onChange({...data,entries:data.entries.filter(x=>x.id!==e.id)})}}><Trash2 size={16}/></button></div>):<p className="nutrition-empty">Nothing logged for this day yet.</p>}</div>
  {added&&<div className="nutrition-undo" role="status"><span><strong>{added.name}</strong> added.</span><button className="text-button" onClick={()=>{onChange({...data,entries:data.entries.filter(e=>e.id!==added.id)});setAdded(null)}}>Undo</button></div>}{removed&&<div className="nutrition-undo" role="status">Entry removed.<button className="text-button" onClick={()=>{if(!data.entries.some(e=>e.id===removed.id))onChange({...data,entries:[...data.entries,removed]});setRemoved(null)}}>Undo</button></div>}
  <details className="nutrition-history"><summary>Daily history</summary><p>Totals reflect logged entries, not necessarily full days.</p>{days.slice(0,30).map(date=>{const t=nutritionTotals(data.entries,date);return <button className="nutrition-day" key={date} onClick={()=>setDay(date)}><strong>{date}</strong><span>{t.calories} kcal · {t.protein} g protein{t.missingCalories||t.missingProtein?' · Partial':''}</span></button>})}{!days.length&&<p>Your daily totals will appear here after your first entry.</p>}<p>Showing the latest 30 logged days. Use the date picker to open any earlier day.</p></details>
 </div>}
 <Dialog open={!!editing} onOpenChange={open=>{if(!open)setEditing(null)}}><DialogContent className="app-dialog"><DialogHeader><DialogTitle>{data.entries.some(e=>e.id===editing?.id)?'Edit nutrition entry':mode==='total'?'Enter daily total':'Log food or meal'}</DialogTitle><DialogDescription>{mode==='total'?'Copy the calorie and protein totals from another tracker. This does not connect or sync that app.':'Add the portion you ate. Giving it a name makes it available under “Have it again.”'}</DialogDescription></DialogHeader><form onSubmit={e=>{e.preventDefault();if(!editing)return;const c=parse(calories),p=parse(protein);if(!valid(c)||!valid(p)||c===null&&p===null||!entryDate||entryDate>today){setError('Enter calories or protein as a nonnegative number, and choose today or an earlier date.');return}const entry={...editing,date:entryDate,name:name.trim(),calories:c,protein:p};onChange({...data,entries:data.entries.some(x=>x.id===entry.id)?data.entries.map(x=>x.id===entry.id?entry:x):[...data.entries,entry]});setDay(entryDate);setEditing(null);setAdded(null)}}>{mode==='total'&&entries.length>0&&<p className="nutrition-warning">This day already has {entries.length} {entries.length===1?'entry':'entries'}. This total will be added to them, so remove any overlap to avoid double-counting.</p>}{mode==='food'?<label>Food or meal name <input autoFocus value={name} maxLength={100} placeholder="Chicken bowl, protein shake…" onChange={e=>setName(e.target.value)}/></label>:<input type="hidden" value={name} readOnly/>}<div className="form-grid"><label>Calories eaten<input autoFocus={mode==='total'} type="number" min={0} step="any" inputMode="decimal" value={calories} placeholder="0" onChange={e=>setCalories(e.target.value)}/></label><label>Protein (g)<input type="number" min={0} step="any" inputMode="decimal" value={protein} placeholder="0" onChange={e=>setProtein(e.target.value)}/></label></div><label>Date<input required type="date" max={today} value={entryDate} onChange={e=>setEntryDate(e.target.value)}/></label>{error&&<p role="alert" className="plan-error">{error}</p>}<button className="primary full">{data.entries.some(e=>e.id===editing?.id)?'Save changes':entryDate===today?'Add to today':'Add entry'}</button></form></DialogContent></Dialog>
 <Dialog open={settings} onOpenChange={setSettings}><DialogContent className="app-dialog"><DialogHeader><DialogTitle>Daily nutrition targets</DialogTitle><DialogDescription>Set your own targets, or leave either blank to track without a target.</DialogDescription></DialogHeader><form onSubmit={e=>{e.preventDefault();const c=parse(calorieTarget),p=parse(proteinTarget);if(!valid(c)||!valid(p)||c===0||p===0){setError('Targets must be greater than zero, or left blank.');return}onChange({...data,calorieTarget:c,proteinTarget:p});setSettings(false)}}><label>Calories per day<input type="number" min={1} step="any" value={calorieTarget} onChange={e=>setCalorieTarget(e.target.value)} placeholder="Optional"/></label><label>Protein per day (g)<input type="number" min={1} step="any" value={proteinTarget} onChange={e=>setProteinTarget(e.target.value)} placeholder="Optional"/></label><p className="form-help">Targets can be changed anytime. Workout calories appear separately because they are estimates, not your total daily expenditure.</p>{error&&<p className="plan-error" role="alert">{error}</p>}<button className="primary full">Save targets</button></form></DialogContent></Dialog>
 </section>;
}
