'use client';
import {useEffect,useRef,useState} from 'react';
import {ArrowRight,ArrowLeft,Check,Loader2,Sparkles} from 'lucide-react';
import {AIConnection} from './ai-connection';
import {onboardingSchema,emptyOnboarding,extractedProfile,type OnboardingDraft} from '@/lib/onboarding';
import {profileSchema} from '@/lib/profile';
import {planSchema} from '@/lib/plan';
import {exerciseLibrary} from '@/lib/exercise-library';
const modes=[{id:'coach',title:'Help me get started'},{id:'routine',title:'I already have a routine'},{id:'manual',title:'I’ll set things up myself'}] as const;
export function Onboarding({onDone}:{onDone:(intent:'plan'|'log'|'explore')=>void}){
 const [invalid,setInvalid]=useState<Record<string,boolean>>({});
 const [draft,setDraft]=useState<OnboardingDraft>(emptyOnboarding()),[loaded,setLoaded]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[saveStatus,setSaveStatus]=useState(''),[conflict,setConflict]=useState(false);
 const followup=draft.reply;
 function setFollowup(reply:string){change({...draft,reply})}
 const revision=useRef<string|null>(null),accountRevision=useRef<string|null>(null),queue=useRef<Promise<unknown>>(Promise.resolve()),dirty=useRef(false),alive=useRef(true),current=useRef(draft),pending=useRef(false);
 current.current=draft;
 useEffect(()=>{alive.current=true;void load();return()=>{alive.current=false}},[]);
 async function load(){setError('');setLoaded(false);setConflict(false);setInvalid({});try{const r=await fetch('/api/onboarding',{cache:'no-store'}),b=await r.json() as {error?:string;complete?:boolean;updatedAt:string|null;accountUpdatedAt:string|null;draft:unknown};if(!r.ok)throw new Error(b.error||'Unable to load setup.');if(b.complete){onDone('explore');return}revision.current=b.updatedAt;accountRevision.current=b.accountUpdatedAt;setDraft(onboardingSchema.parse(b.draft));dirty.current=false;setLoaded(true);setSaveStatus(b.updatedAt?'Setup restored':'');}catch(e){setError((e as Error).message)}}
 function change(next:OnboardingDraft){dirty.current=true;setSaveStatus('Unsaved changes');setDraft(next)}
 function persist(next:OnboardingDraft){
 const task=queue.current.catch(()=>{}).then(async()=>{setSaveStatus('Saving setup…');const r=await fetch('/api/onboarding',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({draft:next,baseUpdatedAt:revision.current})}),b=await r.json() as {error?:string;complete?:boolean;updatedAt:string|null;accountUpdatedAt:string|null;draft:unknown};if(!r.ok){if(r.status===409)setConflict(true);throw new Error(b.error||'Could not save setup.')}revision.current=b.updatedAt;if(alive.current){setSaveStatus('Setup saved');if(current.current===next)dirty.current=false;}return b;});queue.current=task;return task;
 }
 useEffect(()=>{if(!loaded||!dirty.current||busy||conflict)return;const timer=setTimeout(()=>{void persist(draft).catch(e=>{setSaveStatus('Not saved');setError(e.message)})},650);return()=>clearTimeout(timer)},[draft,loaded,busy,conflict]);
 useEffect(()=>{function leaving(e:BeforeUnloadEvent){if(dirty.current){e.preventDefault();e.returnValue=''}}window.addEventListener('beforeunload',leaving);return()=>window.removeEventListener('beforeunload',leaving)},[]);
 async function generate(){
 if(pending.current||conflict||Object.values(invalid).some(Boolean))return;pending.current=true;setBusy(true);setError('');
 const text=draft.messages.length?followup.trim():draft.brief.trim();
 const requestText=draft.messages.length?text:`${draft.mode==='routine'?'Help me keep my existing routine. Turn the session I describe into a usable workout; ask one question only if essential.':'Help me get started. Build a useful first workout from what I share; ask one question only if essential.'}\n${text}`;
 const messages=[...draft.messages,{role:'user' as const,content:requestText}];
 try{await persist(draft);const response=await fetch('/api/plan',{method:'POST',headers:{'Content-Type':'application/json'},signal:AbortSignal.timeout(70000),body:JSON.stringify({onboarding:true,intakeProfile:draft.profile,messages:messages.slice(-10),exercises:exerciseLibrary.map(({id,name,category})=>({id,name,category})),currentPlan:draft.plan})});const body=await response.json() as {error?:string};if(!response.ok)throw new Error(body.error||'Your coach is unavailable. Retry or use manual setup.');const plan=planSchema.parse(body),next={...draft,profile:extractedProfile(draft.profile,plan),reply:'',messages:[...messages,{role:'assistant' as const,content:plan.message}].slice(-100),plan,stage:plan.workouts.length||plan.progress?'review' as const:'brief' as const};change(next);current.current=next;await persist(next);}
 catch(e){setError((e as Error).name==='TimeoutError'?'This is taking longer than expected. Your setup is kept. Retry or continue manually.':(e as Error).message)}finally{pending.current=false;setBusy(false)}
 }
 async function finish(acceptPlan:boolean,intent:'log'|'explore'='explore'){
 if(pending.current||conflict)return;
 if(!draft.profile.sex){setError('Choose a body map to continue.');setDraft({...draft,stage:'review'});return;}
 pending.current=true;setBusy(true);setError('');
 try{await persist(draft);const r=await fetch('/api/onboarding',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({draft,baseUpdatedAt:revision.current,accountUpdatedAt:accountRevision.current,complete:true,acceptPlan})}),b=await r.json() as {error?:string;complete?:boolean;updatedAt:string|null;accountUpdatedAt:string|null;draft:unknown};if(!r.ok){if(r.status===409)setConflict(true);throw new Error(b.error||'Unable to load setup.')}dirty.current=false;onDone(acceptPlan&&draft.plan?.workouts.length?'log':intent)}catch(e){setError((e as Error).message)}finally{pending.current=false;setBusy(false)}
 }
 function field(key:keyof OnboardingDraft['profile'],value:string){const parsed=profileSchema.shape[key].safeParse(!value?null:key==='days'||key==='minutes'?Number(value):value);setInvalid(previous=>({...previous,[key]:!parsed.success}));if(parsed.success)change({...draft,profile:{...draft.profile,[key]:parsed.data}});else setError('Please check '+key+'. Leave optional answers blank if you’re unsure.')}
 function editEntry(wi:number,ei:number,key:'sets'|'reps'|'weight',value:string){if(!draft.plan)return;const numeric=value===''&&key==='weight'?null:Number(value);const entry=planSchema.shape.workouts.element.shape.entries.element.safeParse({...draft.plan.workouts[wi].entries[ei],[key]:numeric});setInvalid(previous=>({...previous,['entry-'+wi+'-'+ei+'-'+key]:!entry.success}));if(!entry.success){setError('Check the workout numbers: sets 1–20, reps 1–100, weight 0–2000 lb.');return;}change({...draft,plan:{...draft.plan,workouts:draft.plan.workouts.map((w,i)=>i===wi?{...w,entries:w.entries.map((e,j)=>j===ei?entry.data:e)}:w)}})}
 const review=draft.stage==='review',lastReply=[...draft.messages].reverse().find(m=>m.role==='assistant')?.content;
 return <main className="onboarding"><header className="onboarding-header"><span className="interview-brand"><Sparkles/> stride.</span><span role="status">{saveStatus}</span></header><section className="panel onboarding-panel" aria-busy={busy}>
 {!loaded?<><h1>Let’s find your starting point.</h1>{!error&&<p role="status">Loading your setup…</p>}</>:<>
 <div className="onboarding-step"><span className={!review?'active':''}>Your training</span><span aria-hidden="true">/</span><span className={review?'active':''}>Your starting point</span></div>
 {review?<><button className="text-button" disabled={busy} onClick={()=>change({...draft,stage:'brief'})}><ArrowLeft size={16}/> Back to your brief</button><h1>{draft.plan?.workouts.length?'A starting point built around you.':'Make Stride yours.'}</h1><p>{draft.plan?'Review the details below. Adjust anything before saving.':'Only your body map is required. Everything else can wait.'}</p></>:<><h1>What does training look like for you?</h1><p>Tell Stride what you want to do and what you have to work with.</p><div className="onboarding-modes" aria-label="How you want to start">{modes.map(m=><button key={m.id} disabled={busy} aria-pressed={draft.mode===m.id} className={draft.mode===m.id?'selected':''} onClick={()=>change({...draft,mode:m.id,stage:m.id==='manual'?'review':'brief'})}>{m.title}</button>)}</div>
 <form onSubmit={e=>{e.preventDefault();void generate()}}>
 {!draft.messages.length?<label className="onboarding-brief">{draft.mode==='routine'?'Describe a session from your routine':'Your training brief'}<textarea autoFocus rows={5} maxLength={3000} disabled={busy} value={draft.brief} placeholder={draft.mode==='routine'?'What exercises, sets and reps do you do? Include working weights if you know them, and anything you want to keep or change.':'For example: I’m new to lifting, want to feel stronger, and have dumbbells at home. I can train twice a week for 30 minutes.'} onChange={e=>change({...draft,brief:e.target.value})}/><small>Goals, equipment and a realistic schedule are a good start. Mention any movements to avoid if you’d like.</small></label>:<><div className="onboarding-reply"><Sparkles size={20}/><p>{lastReply}</p></div><label>Your reply<textarea rows={3} disabled={busy} value={followup} maxLength={3000} onChange={e=>setFollowup(e.target.value)} placeholder="Add a detail, ask for a change, or say what you’re unsure about."/></label></>}
 <button className="primary full" disabled={busy||conflict||!(draft.messages.length?followup.trim():draft.brief.trim())}>{busy?<><Loader2 className="plan-spin" size={18}/> Building your starting point…</>:<>{draft.messages.length?'Update my starting point':'Find my starting point'}<ArrowRight size={18}/></>}</button>
 </form><div className="onboarding-bottom"><button className="text-button" disabled={busy} onClick={()=>change({...draft,stage:'review'})}>Skip coaching and start logging</button><AIConnection/></div><small className="onboarding-note">Your brief is sent to OpenAI when you ask your coach. Setup is saved to your account; training changes wait for your approval.</small></>}
 {review&&<>
 {lastReply&&<div className="onboarding-reply"><Sparkles size={20}/><p>{lastReply}</p></div>}
 <div className="onboarding-profile"><h2>{draft.plan?'What Stride understood':'Your profile'}</h2><div className="onboarding-fields">
 <label>Name · optional<input maxLength={80} disabled={busy} value={draft.profile.name||''} onChange={e=>field('name',e.target.value)}/></label>
 <label>Body map · required<select disabled={busy} value={draft.profile.sex||''} onChange={e=>field('sex',e.target.value)}><option value="">Choose a body map</option><option value="Male">Male</option><option value="Female">Female</option></select><small>Sets your profile’s sex for the body map and fitness references.</small></label>
 <label>Goal · optional<input disabled={busy} maxLength={1000} defaultValue={draft.profile.goal||''} key={'goal-'+draft.messages.length} onBlur={e=>field('goal',e.target.value)}/></label>
 <label>Equipment · optional<input disabled={busy} maxLength={1000} defaultValue={draft.profile.equipment||''} key={'equipment-'+draft.messages.length} onBlur={e=>field('equipment',e.target.value)}/></label>
 </div><details open={draft.mode==='manual'?true:undefined}><summary>Schedule, experience & things to work around</summary><div className="onboarding-fields"><label>Days per week<select disabled={busy} value={draft.profile.days||''} onChange={e=>field('days',e.target.value)}><option value="">Not sure yet</option>{[1,2,3,4,5,6,7].map(x=><option key={x}>{x}</option>)}</select></label><label>Minutes per session<input type="number" min={10} max={180} disabled={busy} defaultValue={draft.profile.minutes||''} key={'minutes-'+draft.messages.length} onBlur={e=>field('minutes',e.target.value)}/></label><label>Experience<select disabled={busy} value={draft.profile.experience||''} onChange={e=>field('experience',e.target.value)}><option value="">Not shared</option>{['New to lifting','Some experience','Experienced'].map(x=><option key={x}>{x}</option>)}</select></label><label>Age range · optional<select disabled={busy} value={draft.profile.ageRange||''} onChange={e=>field('ageRange',e.target.value)}><option value="">Not shared</option>{['Under 18','18–29','30–44','45–59','60+','Prefer not to say'].map(x=><option key={x}>{x}</option>)}</select></label><label>Limitations & preferences<input maxLength={1000} disabled={busy} defaultValue={draft.profile.limitations||''} key={'limitations-'+draft.messages.length} onBlur={e=>field('limitations',e.target.value)}/></label></div></details><p className="onboarding-note">Unknown details stay open. If you change a constraint, ask the coach to revise the workout before saving.</p></div>
 {draft.plan?.workouts.map((w,wi)=><article key={wi+'-'+draft.messages.length} className="onboarding-workout"><div className="onboarding-workout-head"><span className="eyebrow">WORKOUT {wi+1}</span><span>{w.entries.length} exercises</span></div><h2>{w.name}</h2><p>{w.description}</p><div className="onboarding-exercises">{w.entries.map((e,ei)=><div key={ei} className="onboarding-exercise"><strong>{exerciseLibrary.find(x=>x.id===e.exerciseId)?.name||'Exercise'}</strong><div><label>Sets<input type="number" min={1} max={20} disabled={busy} defaultValue={e.sets} onBlur={v=>editEntry(wi,ei,'sets',v.target.value)}/></label><label>Reps<input type="number" min={1} max={100} disabled={busy} defaultValue={e.reps} onBlur={v=>editEntry(wi,ei,'reps',v.target.value)}/></label><label>Weight · lb<input type="number" min={0} max={2000} step={0.5} disabled={busy} defaultValue={e.weight??''} placeholder="Choose later" onBlur={v=>editEntry(wi,ei,'weight',v.target.value)}/></label></div></div>)}</div><small>Start with a comfortable load. Your logged sets will establish a baseline for future targets.</small></article>)}
 {draft.plan?.progress&&<div className="onboarding-workout"><h2>Optional tracking setup</h2>{draft.plan.progress.goal&&<p>Goal: {draft.plan.progress.goal.title} · {draft.plan.progress.goal.target} {draft.plan.progress.goal.unit}</p>}{draft.plan.progress.nutrition&&<p>Daily targets: {draft.plan.progress.nutrition.calorieTarget??'—'} calories · {draft.plan.progress.nutrition.proteinTarget??'—'} g protein</p>}{draft.plan.progress.activityTemplates.map(a=><p key={a.name}>{a.name} · {a.durationMinutes} min · {a.intensity} · {a.scheduleHint}</p>)}<button className="text-button" disabled={busy} onClick={()=>change({...draft,plan:{...draft.plan!,progress:null}})}>Remove tracking suggestions</button></div>}
 {draft.plan&&<form className="onboarding-refine" onSubmit={e=>{e.preventDefault();void generate()}}><label>Want something different?<input disabled={busy} maxLength={3000} value={followup} onChange={e=>setFollowup(e.target.value)} placeholder="Swap an exercise, shorten the session, or clarify a preference"/></label><button className="secondary" disabled={busy||!followup.trim()}>Revise with my coach</button></form>}
 <div className="onboarding-save"><button className="primary full" disabled={busy||conflict||Object.values(invalid).some(Boolean)} onClick={()=>void finish(!!(draft.plan?.workouts.length||draft.plan?.progress),'log')}>{busy?<><Loader2 size={18} className="plan-spin"/> Saving…</>:draft.plan?.workouts.length?<><Check size={18}/> Save & choose my first workout</>:'Save profile & start logging'}</button><button className="text-button" disabled={busy||conflict||Object.values(invalid).some(Boolean)} onClick={()=>void finish(false,'explore')}>{draft.plan?'Continue without these suggestions':'Save profile & explore'}</button></div>
 </>}
 </>}
 {error&&<div className="onboarding-error" role="alert"><p>{error}</p>{(!loaded||conflict)?<button className="secondary" onClick={()=>void load()}>Load saved setup</button>:<button className="text-button" disabled={busy} onClick={()=>void persist(draft).then(()=>setError('')).catch(e=>setError(e.message))}>Retry saving setup</button>}</div>}
 </section></main>
}
