'use client';
import {useEffect,useRef,useState} from 'react';
import {Sparkles,Send,Loader2,ArrowRight,Camera,ImagePlus,X} from 'lucide-react';
import {AIConnection} from '@/components/ai-connection';
import {Data} from '@/lib/training';
import {GeneratedPlan,PlanMessage,planSchema,coachingContext} from '@/lib/plan';
import {preparePhoto} from '@/lib/photo';
export type PlannerState={messages:PlanMessage[];plan:GeneratedPlan|null;ids:string[]};
export function PlanChat({data,state,onApply,onReset,onView}:{data:Data;state:PlannerState;onApply:(plan:GeneratedPlan,messages:PlanMessage[])=>void;onReset:()=>void;onView:()=>void}){
 const [photo,setPhoto]=useState(''),[preparing,setPreparing]=useState(false);const camera=useRef<HTMLInputElement>(null),upload=useRef<HTMLInputElement>(null);
 const [input,setInput]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[signInUrl,setSignInUrl]=useState(''),[action,setAction]=useState<{url:string;label:string}|null>(null),[cooldown,setCooldown]=useState(0);const pending=useRef(false);const controller=useRef<AbortController|null>(null);const log=useRef<HTMLDivElement>(null);
 useEffect(()=>{if(cooldown<=0)return;const timer=setTimeout(()=>setCooldown(n=>n-1),1000);return()=>clearTimeout(timer)},[cooldown]);
 useEffect(()=>()=>controller.current?.abort(),[]);
 useEffect(()=>{if(log.current)log.current.scrollTop=log.current.scrollHeight},[state.messages,busy,error]);
 async function choosePhoto(file?:File){
  if(!file)return;
  if(state.messages.filter(m=>m.photo).length>=3){setError('You can include up to three photos. Remove an earlier photo or start a new plan first.');return}
  setPreparing(true);setError('');try{setPhoto(await preparePhoto(file))}catch(e){setError(e instanceof Error?e.message:'This photo could not be opened.')}finally{setPreparing(false)}
 }
 async function send(){
  if(pending.current||preparing||cooldown>0||(!input.trim()&&!photo))return;
  pending.current=true;setBusy(true);setError('');setSignInUrl('');setAction(null);
  const messages:PlanMessage[]=[...state.messages.slice(-10),{role:'user',content:input.trim()||'Use this photo as context to help me choose a workout plan. Ask about my goals and equipment if needed.',...(photo?{photo}:{})}];
  controller.current=new AbortController();const timeout=setTimeout(()=>controller.current?.abort(),70000);
  try{
   const response=await fetch('/api/plan',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({messages,exercises:data.exercises.map(({id,name,category})=>({id,name,category})),currentPlan:state.plan,training:coachingContext(data)}),signal:controller.current.signal});
   const body=await response.json();if(!response.ok){if(['https://platform.openai.com/settings/organization/billing','https://platform.openai.com/settings/organization/limits'].includes(body.actionUrl))setAction({url:body.actionUrl,label:body.actionLabel});if(body.retryAfter>0)setCooldown(Math.min(3600,Math.ceil(body.retryAfter)));}if(response.status===401&&body.signInUrl?.startsWith('/signin-with-chatgpt?'))setSignInUrl(body.signInUrl);if(!response.ok)throw new Error(body.error||'Unable to create your plan. Try again.');
   const plan=planSchema.parse(body);onApply(plan,[...messages,{role:'assistant',content:plan.message}]);setInput('');setPhoto('');
  }catch(e){setError(e instanceof Error&&e.name==='AbortError'?'That took too long. Your existing workouts are unchanged. Please try again.':e instanceof Error?e.message:'Unable to create your plan. Please try again.')}
  finally{clearTimeout(timeout);pending.current=false;setBusy(false)}
 }
 return <section className="panel plan-chat"><div className="section-head"><div><h2><Sparkles size={20}/> Your training coach</h2><p>Talk through your goals, share a photo, and build a plan you can train from.</p></div><div className="plan-header-actions"><AIConnection/>{state.messages.length>0&&<button disabled={busy||preparing} className="text-button" onClick={()=>{onReset();setError('');setInput('');setPhoto('');setAction(null)}}>New plan</button>}</div></div>
 {state.messages.length>0&&<div className="plan-messages" ref={log} role="log" aria-label="Workout planning conversation">{state.messages.map((m,i)=><div key={i} className={'plan-message '+m.role}><strong>{m.role==='user'?'You':'Stride'}</strong><p>{m.content}</p>{m.photo&&<div className="chat-photo"><img src={m.photo} alt="Photo shared with your training coach"/><button type="button" className="text-button" disabled={busy} onClick={()=>onApply({message:'Photo removed',workouts:[]},state.messages.map((entry,index)=>index===i?{role:entry.role,content:entry.content}:entry))}>Remove photo</button></div>}</div>)}</div>}
 {state.ids.length>0&&<div className="plan-saved"><span>{state.ids.filter(id=>data.templates.some(t=>t.id===id)).length} workout templates created</span><button className="text-button" onClick={onView}>View templates <ArrowRight size={16}/></button></div>}
 <form onSubmit={e=>{e.preventDefault();void send()}}><label htmlFor="plan-request">{state.plan?'What would you like to change?':state.messages.length?'Tell your coach more':'What would you like to train for?'}</label><textarea id="plan-request" rows={3} maxLength={4000} value={input} disabled={busy} onChange={e=>setInput(e.target.value)} placeholder="For example: I want to build my shoulders and back. I have dumbbells and 3 days a week. What plan would you suggest?"/><div className="photo-controls"><input ref={camera} type="file" accept="image/*" capture="user" hidden aria-label="Take a coaching photo" onChange={e=>{void choosePhoto(e.target.files?.[0]);e.target.value=''}}/><input ref={upload} type="file" accept="image/*" hidden aria-label="Choose a coaching photo" onChange={e=>{void choosePhoto(e.target.files?.[0]);e.target.value=''}}/><button type="button" className="secondary" disabled={busy||preparing} onClick={()=>camera.current?.click()}><Camera size={17}/> Take photo</button><button type="button" className="secondary" disabled={busy||preparing} onClick={()=>upload.current?.click()}><ImagePlus size={17}/> Upload photo</button></div>{preparing&&<p role="status">Preparing your photo…</p>}{photo&&<div className="photo-preview"><img src={photo} alt="Photo ready to send"/><button type="button" className="icon-button" disabled={busy} aria-label="Remove attached photo" onClick={()=>setPhoto('')}><X size={18}/></button><span>Ready to send with your message</span></div>}<p className="photo-privacy">Optional photos are sent to OpenAI with your message. Stride keeps them only in this open conversation; starting a new plan or reloading clears them.</p><div className="plan-submit"><p>{state.plan?'Changes update the templates from this conversation.':'Include any exercises you want to avoid.'}</p><button className="primary" disabled={busy||preparing||cooldown>0||(!input.trim()&&!photo)}>{busy?<Loader2 className="plan-spin" size={18}/>:<Send size={18}/>} {busy?'Creating…':cooldown>0?`Try again in ${cooldown}s`:state.plan?'Update plan':'Send'}</button></div>{busy&&<p role="status">Putting your plan together…</p>}{error&&<p className="plan-error" role="alert">{error}</p>}{action&&<a className="text-button" href={action.url} target="_blank" rel="noopener noreferrer">{action.label}</a>}{signInUrl&&<a className="primary" href={signInUrl} target="_top">Sign in with ChatGPT</a>}</form></section>
}
