'use client';
import {useEffect,useState} from 'react';
import {Sparkles} from 'lucide-react';
import {CoachingProfile,profileSchema} from '@/lib/profile';
const steps=[
 {key:'name',question:'What should I call you?',hint:'Let’s make this your training space.'},
 {key:'ageRange',question:'Which age range are you in?',options:['Under 18','18–29','30–44','45–59','60+','Prefer not to say']},
 {key:'goal',question:'What would you like training to help you achieve?',hint:'Tell me what matters most. Include a target or timeline if you have one.'},
 {key:'experience',question:'How much lifting experience do you have?',options:['New to lifting','Some experience','Experienced']},
 {key:'days',question:'How many days a week can you realistically train?',options:['1','2','3','4','5','6','7']},
 {key:'minutes',question:'How many minutes can you give each workout?',hint:'Choose between 10 and 180 minutes.'},
 {key:'equipment',question:'What equipment will you train with?',hint:'Home or gym? Include available weights and any limits, such as dumbbells up to 35 lb. Bodyweight only is fine.'},
 {key:'limitations',question:'What should I work around?',hint:'Movements to avoid, other sports, recovery needs, or restrictions. Enter “None” if nothing applies; you can also choose not to share.'},
] as const;
export function ProfileGate({children}:{children:React.ReactNode}){
 const [loading,setLoading]=useState(true),[complete,setComplete]=useState(false),[draft,setDraft]=useState<Record<string,string>>({}),[step,setStep]=useState(0),[error,setError]=useState(''),[busy,setBusy]=useState(false),[ai,setAI]=useState(false),[reply,setReply]=useState('');
 async function load(){setLoading(true);setError('');try{const r=await fetch('/api/profile',{cache:'no-store'}),body=await r.json() as {profile?:CoachingProfile;error?:string};if(!r.ok)throw new Error(body.error);if(body.profile){setDraft(Object.fromEntries(Object.entries(body.profile).map(([k,v])=>[k,String(v)])));setComplete(true)}setLoading(false)}catch(e){setError(e instanceof Error?e.message:'Could not load your profile.');setLoading(false)}}
 useEffect(()=>{void load();fetch('/api/ai-connection',{cache:'no-store'}).then(r=>r.json()).then((b:unknown)=>setAI(!!(b as {connected?:boolean}).connected)).catch(()=>{})},[]);
 if(loading)return <div className="loading">Loading your coaching profile…</div>;
 if(complete)return <><div className="profile-access"><button className="text-button" onClick={()=>{setComplete(false);setStep(8)}}>Your coaching profile</button></div>{children}</>;
 const current=steps[step],value=current?draft[current.key]||'':'';
 const profile={...draft,days:Number(draft.days),minutes:Number(draft.minutes)};
 async function next(){setError('');if(!current)return;const field=profileSchema.shape[current.key];if(!field.safeParse(current.key==='days'||current.key==='minutes'?Number(value):value).success){setError('Please answer this question before continuing.');return}if(ai&&!reply&&['goal','equipment','limitations'].includes(current.key)){setBusy(true);try{const r=await fetch('/api/interview',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({question:current.question,answer:value,profile:draft})}),b=await r.json() as {message?:string;error?:string};if(!r.ok)throw new Error(b.error);setReply(b.message||'Thanks. Continue when you’re ready.')}catch(e){setReply('Your answers are kept. You can continue without AI.');setError(e instanceof Error?e.message:'AI unavailable.')}finally{setBusy(false)}return}setStep(step+1);setReply('')}
 async function save(){setError('');if(!profileSchema.safeParse(profile).success){setError('Please complete all interview answers before saving.');return}setBusy(true);try{const r=await fetch('/api/profile',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(profile)}),b=await r.json() as {error?:string};if(!r.ok)throw new Error(b.error);localStorage.removeItem('stride-v1');setComplete(true)}catch(e){setError(e instanceof Error?e.message:'Could not save. Please retry.')}finally{setBusy(false)}}
 return <main className="interview"><div className="interview-brand"><Sparkles/> stride.</div><section className="panel"><span className="eyebrow">Your coaching interview · {step<8?`${step+1} of 8`:'Review'}</span><progress aria-label="Interview progress" max={8} value={step}/>{current?<><h1>{current.question}</h1>{'hint' in current&&<p>{current.hint}</p>}<form onSubmit={e=>{e.preventDefault();void next()}}>{'options' in current?<div className="interview-options">{current.options.map(option=><button type="button" aria-pressed={value===option} className={value===option?'primary':'secondary'} key={option} disabled={busy} onClick={()=>setDraft({...draft,[current.key]:option})}>{option}</button>)}</div>:<label><span className="sr-only">{current.question}</span>{current.key==='name'||current.key==='minutes'?<input autoFocus key={current.key} value={value} type={current.key==='minutes'?'number':'text'} min={10} max={180} maxLength={80} disabled={busy} onChange={e=>setDraft({...draft,[current.key]:e.target.value})}/>:<textarea key={current.key} rows={4} maxLength={1000} disabled={busy} value={value} onChange={e=>setDraft({...draft,[current.key]:e.target.value})}/>}</label>}{reply&&<div className="plan-message assistant" role="status"><strong>Stride</strong><p>{reply}</p><small>You can add detail above before continuing.</small></div>}<div className="button-group">{step>0&&<button type="button" className="secondary" disabled={busy} onClick={()=>{setStep(step-1);setReply('');setError('')}}>Back</button>}<button className="primary" disabled={busy}>{busy?'Thinking…':reply?'Continue':'Next'}</button></div></form></>:<><h1>Does this sound like you?</h1><p>Your coach will use these answers to tailor plans and advice.</p>{steps.map((s,i)=><div className="interview-review" key={s.key}><div><strong>{s.question}</strong><p>{draft[s.key]||'Not answered'}</p></div><button className="text-button" onClick={()=>{setStep(i);setReply('')}}>Edit</button></div>)}<button className="primary full" disabled={busy} onClick={()=>void save()}>{busy?'Saving…':'Save profile & start training'}</button></>}{error&&<p className="plan-error" role="alert">{error}</p>}{error&&step===0&&<button className="text-button" onClick={()=>void load()}>Retry loading profile</button>}<p className="interview-footnote">Complete your profile to enter Stride. You can update it later.</p></section></main>
}
