'use client';
import {useState} from 'react';
import {ArrowRight,Check,Loader2,Send,Sparkles,X} from 'lucide-react';
import {Data} from '@/lib/training';
import {ProgressProposal,applyProgressProposal} from '@/lib/plan';

type Message={role:'user'|'assistant';content:string};
export function ProgressCoach({data,onApply}:{data:Data;onApply:(data:Data)=>void}){
 const [open,setOpen]=useState(false),[messages,setMessages]=useState<Message[]>([]),[input,setInput]=useState(''),[proposal,setProposal]=useState<ProgressProposal|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState('');
 async function send(){if(!input.trim()||busy)return;const next=[...messages,{role:'user' as const,content:input.trim()}];setMessages(next);setInput('');setBusy(true);setError('');setProposal(null);try{const response=await fetch('/api/progress-coach',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({messages:next.slice(-12),context:{goals:(data.goals||[]).map(g=>({title:g.title,kind:g.kind,target:g.target,unit:g.unit,deadline:g.deadline})),nutrition:{calorieTarget:data.nutrition?.calorieTarget??null,proteinTarget:data.nutrition?.proteinTarget??null},exercises:data.exercises.map(e=>({id:e.id,name:e.name}))}})}),body=await response.json();if(!response.ok)throw new Error(body.error||'Your coach could not respond.');setMessages([...next,{role:'assistant',content:body.message}]);setProposal(body.proposal)}catch(e){setError(e instanceof Error?e.message:'Your coach could not respond.')}finally{setBusy(false)}}
 function apply(){if(!proposal)return;onApply(applyProgressProposal(data,proposal));setProposal(null);setMessages(m=>[...m,{role:'assistant',content:'Saved. I’ll use these targets as context when helping with your training.'}])}
 if(!open)return <section className="panel progress-coach-intro"><div><Sparkles size={20}/><span><strong>Set targets with your coach</strong><small>Create a goal or calorie and protein targets through conversation.</small></span></div><button className="secondary" onClick={()=>setOpen(true)}>Talk to your coach <ArrowRight size={16}/></button></section>;
 return <section className="panel progress-coach"><div className="section-head"><div><h2><Sparkles size={19}/> Progress coach</h2><p>Tell me what you want to accomplish. I’ll help make it trackable.</p></div><button className="icon-button" aria-label="Close progress coach" onClick={()=>setOpen(false)}><X size={18}/></button></div>{messages.length>0&&<div className="progress-coach-messages">{messages.map((m,i)=><div className={'plan-message '+m.role} key={i}><strong>{m.role==='user'?'You':'Stride'}</strong><p>{m.content}</p></div>)}</div>}{proposal&&<div className="progress-proposal"><strong>Ready to add</strong>{proposal.goal&&<span>{proposal.goal.title} · Target {proposal.goal.target} {proposal.goal.unit}</span>}{proposal.nutrition?.calorieTarget&&<span>{proposal.nutrition.calorieTarget} calories per day</span>}{proposal.nutrition?.proteinTarget&&<span>{proposal.nutrition.proteinTarget} g protein per day</span>}<button className="primary" onClick={apply}><Check size={16}/> Apply targets</button></div>}<form onSubmit={e=>{e.preventDefault();void send()}}><label htmlFor="progress-coach-input">{messages.length?'Reply to your coach':'What would you like to work toward?'}</label><textarea id="progress-coach-input" rows={2} value={input} maxLength={4000} disabled={busy} onChange={e=>setInput(e.target.value)} placeholder="For example: I want to lose 10 lb over the next 12 weeks and set nutrition targets."/><button className="primary" disabled={busy||!input.trim()}>{busy?<Loader2 className="plan-spin" size={17}/>:<Send size={17}/>} Send</button>{error&&<p className="plan-error" role="alert">{error}</p>}</form></section>
}
