'use client';
import {useEffect,useState} from 'react';
import {Timer,Plus,X,Trophy} from 'lucide-react';
import {toast} from 'sonner';
import {Data,Workout} from '@/lib/training';

export function RestFeedback({data,workout}:{data:Data;workout:Workout}){
 const [until,setUntil]=useState(0),[remaining,setRemaining]=useState(0),[label,setLabel]=useState('');
 useEffect(()=>{const selectValue=(event:FocusEvent)=>{const input=event.target as HTMLInputElement;if(input.matches('.set-input input[type=number]'))requestAnimationFrame(()=>input.select())};document.addEventListener('focusin',selectValue);return()=>document.removeEventListener('focusin',selectValue)},[]);
 useEffect(()=>{const tick=()=>setRemaining(Math.max(0,Math.ceil((until-Date.now())/1000)));tick();const timer=setInterval(tick,250);return()=>clearInterval(timer)},[until]);
 useEffect(()=>{if(until&&remaining===0){toast.success('Rest complete — ready for your next set.');setUntil(0)}},[remaining,until]);
 useEffect(()=>{function completed(event:Event){const detail=(event as CustomEvent<{exerciseId:string;weight:number;reps:number;targetWeight:number;targetReps:number}>).detail;if(!detail)return;const exercise=data.exercises.find(e=>e.id===detail.exerciseId),entry=exercise&&workout.entries.find(e=>e.exerciseId===exercise.id);if(!exercise||!entry)return;const {weight,reps,targetWeight,targetReps}=detail,score=weight*(1+reps/30);const prior=data.workouts.filter(w=>w.id!==workout.id).flatMap(w=>w.entries.filter(e=>e.exerciseId===exercise.id).flatMap(e=>e.sets.filter(s=>s.status==='completed'||s.status==='modified'))).concat(entry.sets.filter(s=>s.status==='completed'||s.status==='modified'));const best=Math.max(0,...prior.map(s=>s.weight*(1+s.reps/30))),weightBest=Math.max(0,...prior.map(s=>s.weight));if(prior.length&&(score>best+.01||weight>weightBest)){toast.success(`New ${exercise.name} record — ${weight} lb × ${reps}!`,{icon:<Trophy size={18}/>});setLabel('Personal record — take a good rest.')}else if(!prior.length){toast.success(`First ${exercise.name} set logged — baseline established.`);setLabel('Nice work. Recover for the next set.')}else if(weight>=targetWeight&&reps>=targetReps){toast.success('Set complete — target hit.');setLabel('Target hit. Recover for the next set.')}else{toast.success('Set complete. Keep building.');setLabel('Set logged. Recover for the next set.')}setUntil(Date.now()+90000);setRemaining(90)}window.addEventListener('stride:set-recorded',completed);return()=>window.removeEventListener('stride:set-recorded',completed)},[data,workout]);
 if(!until)return <div className="rest-timer-launch"><button className="secondary" onClick={()=>{setLabel('Rest timer');setUntil(Date.now()+90000);setRemaining(90)}}><Timer size={17}/> Start 1:30 rest</button></div>;const minutes=Math.floor(remaining/60),seconds=String(remaining%60).padStart(2,'0');return <aside className={'rest-timer '+(!remaining?'complete':'')} aria-live="polite"><span className="rest-icon"><Timer size={22}/></span><div><small>{label}</small><strong>{minutes}:{seconds}</strong></div><button className="secondary" onClick={()=>{setUntil(v=>v+30000);setRemaining(v=>v+30)}}><Plus size={16}/> 30 sec</button><button className="icon-button" aria-label="End rest timer" onClick={()=>setUntil(0)}><X size={18}/></button></aside>
}
