'use client';
import {useEffect,useState} from 'react';
import {Timer,Plus,X,Trophy} from 'lucide-react';
import {toast} from 'sonner';
import {Data,Workout} from '@/lib/training';

export function RestFeedback({data,workout}:{data:Data;workout:Workout}){
 const [until,setUntil]=useState(0),[remaining,setRemaining]=useState(0),[label,setLabel]=useState('');
 useEffect(()=>{const selectValue=(event:FocusEvent)=>{const input=event.target as HTMLInputElement;if(input.matches('.set-input input[type=number]'))requestAnimationFrame(()=>input.select())};document.addEventListener('focusin',selectValue);return()=>document.removeEventListener('focusin',selectValue)},[]);
 useEffect(()=>{const tick=()=>setRemaining(Math.max(0,Math.ceil((until-Date.now())/1000)));tick();const timer=setInterval(tick,250);return()=>clearInterval(timer)},[until]);
 useEffect(()=>{if(until&&remaining===0){toast.success('Rest complete — ready for your next set.');setUntil(0)}},[remaining,until]);
 useEffect(()=>{function completed(event:MouseEvent){const button=(event.target as HTMLElement).closest<HTMLButtonElement>('.done-button');if(!button||button.classList.contains('is-done'))return;const panel=button.closest<HTMLElement>('.log-panel'),row=button.closest<HTMLElement>('.set-row'),name=panel?.querySelector('h2')?.textContent,inputs=row?.querySelectorAll<HTMLInputElement>('input[type=number]');if(!name||!inputs?.length)return;const exercise=data.exercises.find(e=>e.name===name),entry=exercise&&workout.entries.find(e=>e.exerciseId===exercise.id);if(!exercise||!entry)return;const weight=Number(inputs[0].value),reps=Number(inputs[1].value),score=weight*(1+reps/30);const prior=data.workouts.filter(w=>w.id!==workout.id).flatMap(w=>w.entries.filter(e=>e.exerciseId===exercise.id).flatMap(e=>e.sets.filter(s=>s.status==='completed'||s.status==='modified'))).concat(entry.sets.filter(s=>s.status==='completed'||s.status==='modified'));const best=Math.max(0,...prior.map(s=>s.weight*(1+s.reps/30))),weightBest=Math.max(0,...prior.map(s=>s.weight));if(prior.length&&(score>best+.01||weight>weightBest)){toast.success(`New ${exercise.name} record — ${weight} lb × ${reps}!`,{icon:<Trophy size={18}/>});setLabel('Personal record — take a good rest.')}else if(!prior.length){toast.success(`First ${exercise.name} set logged — baseline established.`);setLabel('Nice work. Recover for the next set.')}else if(weight>=Number(inputs[0].defaultValue||weight)&&reps>=Number(inputs[1].defaultValue||reps)){toast.success('Set complete — target hit.');setLabel('Target hit. Recover for the next set.')}else{toast.success('Set complete. Keep building.');setLabel('Set logged. Recover for the next set.')}const end=Date.now()+90000;setUntil(end);setRemaining(90)}document.addEventListener('click',completed,true);return()=>document.removeEventListener('click',completed,true)},[data,workout]);
 if(!until)return null;const minutes=Math.floor(remaining/60),seconds=String(remaining%60).padStart(2,'0');return <aside className={'rest-timer '+(!remaining?'complete':'')} aria-live="polite"><span className="rest-icon"><Timer size={22}/></span><div><small>{label}</small><strong>{minutes}:{seconds}</strong></div><button className="secondary" onClick={()=>{setUntil(v=>v+30000);setRemaining(v=>v+30)}}><Plus size={16}/> 30 sec</button><button className="icon-button" aria-label="End rest timer" onClick={()=>setUntil(0)}><X size={18}/></button></aside>
}
