'use client';
import {useEffect,useRef,useState} from 'react';
import {Sparkles,Send,Loader2,Check,X} from 'lucide-react';
import {AIConnection} from '@/components/ai-connection';
import {Data,Workout} from '@/lib/training';
import {applySessionChanges} from '@/lib/apply-session-changes';
import {SessionCoachReply,sessionCoachSchema} from '@/lib/session-coach';
import {coachingContext} from '@/lib/adaptive-coach';
import {goalProgress} from '@/lib/goals';
import {useCoachMemory} from '@/components/coach-memory';
import {CoachSaveOffer} from '@/components/coach-save-offer';
type ChatMessage={role:'user'|'assistant';content:string};
export function SessionCoach({data,workout,onApply}:{data:Data;workout:Workout;onApply:(workout:Workout)=>void}){const {messages:storedMessages,setMessages,setOffer}=useCoachMemory('session:'+workout.id);const messages=storedMessages.length?storedMessages:workout.coachMessages||[];const [input,setInput]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[proposal,setProposal]=useState<SessionCoachReply|null>(null);const latest=useRef(workout);latest.current=workout;const proposalSnapshot=useRef('');const controller=useRef<AbortController|null>(null);useEffect(()=>{controller.current?.abort();setProposal(null);setError('')},[workout.id]);useEffect(()=>()=>controller.current?.abort(),[]);const exerciseName=(id:string)=>data.exercises.find(e=>e.id===id)?.name||'exercise';const describe=(c:SessionCoachReply['changes'][number])=>c.type==='replace_exercise'?`Replace ${exerciseName(c.exerciseId)} with ${exerciseName(c.replacementExerciseId||'')}`:c.type==='add_exercise'?`Add ${exerciseName(c.exerciseId)}`:c.type==='remove_exercise'?`Remove ${exerciseName(c.exerciseId)}`:c.type==='rename_workout'?`Rename workout to “${c.name}”`:`Adjust ${exerciseName(c.exerciseId)}${c.sets?` to ${c.sets} sets`:''}${c.reps?` × ${c.reps} reps`:''}${c.weight!==null?` at ${c.weight} lb`:''}`;
async function send(prompt=input){if(busy||!prompt.trim())return;const next=[...messages.slice(-10),{role:'user' as const,content:prompt.trim()}];setBusy(true);setError('');setProposal(null);controller.current=new AbortController();try{const response=await fetch('/api/session-coach',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({messages:next,workout,context:JSON.stringify({...coachingContext(data),goalProgress:(data.goals||[]).filter(g=>!g.archived).map(g=>({title:g.title,...goalProgress(g,data)}))}).slice(0,100000),exercises:data.exercises.map(({id,name,category})=>({id,name,category}))}),signal:controller.current.signal});const body=await response.json() as SessionCoachReply & {error?:string};if(!response.ok)throw new Error(body.error||'Your coach could not respond.');if(latest.current.id!==workout.id)return;const reply=sessionCoachSchema.parse(body);proposalSnapshot.current=JSON.stringify(workout.entries);const conversation=[...messages,next[next.length-1],{role:'assistant' as const,content:reply.message}].slice(-200);setMessages(conversation);onApply({...latest.current,coachMessages:conversation.slice(-30)});setProposal(reply.changes.length?reply:null);setOffer(reply.saveUpdates||null);setInput('')}catch(e){setError(e instanceof Error?e.message:'Your coach could not respond.')}finally{setBusy(false)}}
function apply(){if(!proposal)return;if(JSON.stringify(workout.entries)!==proposalSnapshot.current){setProposal(null);setError("Your sets changed since this suggestion. Ask me to review them again.");return}const result=applySessionChanges(workout,proposal.changes,data.exercises.map(e=>e.id));if(result.applied){onApply({...result.workout,coachMessages:[...messages,{role:'assistant',content:'Your approved changes were applied to the remaining sets.'}].slice(-30) as ChatMessage[]});setMessages(m=>[...m,{role:'assistant',content:`Applied ${result.applied} change${result.applied===1?'':'s'} to this session. Previously logged sets were kept.`}]);setProposal(null)}setError(result.skipped?'Some changes could not be applied because the exercise or remaining sets changed. Ask your coach for an updated proposal.':result.applied?'':'No changes were applied. Ask your coach for an updated proposal.')}
return <section className="panel session-coach"><div className="section-head"><div><h2><Sparkles size={20}/> Your coach</h2><p>Ask a question, get guidance, or adjust this workout.</p></div><AIConnection/></div><div className="coach-prompts">{["How should I approach today’s workout?","Review my sets and suggest adjustments","How is this helping my goals?"].map(prompt=><button className="secondary" disabled={busy} key={prompt} onClick={()=>void send(prompt)}>{prompt}</button>)}</div>{messages.length>0&&<div className="session-coach-messages" role="log">{messages.map((m,i)=><div key={i} className={'plan-message '+m.role}><strong>{m.role==='user'?'You':'Stride'}</strong><p>{m.content}</p></div>)}</div>}<CoachSaveOffer area={'session:'+workout.id}/>{proposal&&<div className="session-proposal"><strong>Proposed changes</strong>{proposal.changes.map((c,i)=><span key={i}><Check size={15}/>{describe(c)}</span>)}<div><button className="primary" onClick={apply}><Check size={17}/> Apply changes</button><button className="secondary" onClick={()=>setProposal(null)}><X size={17}/> Keep workout</button></div></div>}<form onSubmit={e=>{e.preventDefault();void send()}}><label htmlFor="session-question">Reply to your coach</label><textarea id="session-question" rows={2} maxLength={4000} value={input} disabled={busy} onChange={e=>setInput(e.target.value)} placeholder="I don’t have heavier dumbbells. Can we swap this exercise?"/><button className="primary" disabled={busy||!input.trim()}>{busy?<Loader2 className="plan-spin" size={18}/>:<Send size={18}/>} {busy?'Thinking…':'Ask coach'}</button>{error&&<p className="plan-error" role="alert">{error}</p>}</form></section>}
