'use client';
import {useEffect,useRef,useState} from 'react';
import {Sparkles,Send,Loader2,Check,X} from 'lucide-react';
import {AIConnection} from '@/components/ai-connection';
import {Data,Workout,setOf} from '@/lib/training';
import {SessionCoachReply,sessionCoachSchema} from '@/lib/session-coach';
type ChatMessage={role:'user'|'assistant';content:string};
export function SessionCoach({data,workout,onApply}:{data:Data;workout:Workout;onApply:(workout:Workout)=>void}){const [messages,setMessages]=useState<ChatMessage[]>([]),[input,setInput]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[proposal,setProposal]=useState<SessionCoachReply|null>(null);const controller=useRef<AbortController|null>(null);useEffect(()=>{setMessages([]);setProposal(null);setError('')},[workout.id]);useEffect(()=>()=>controller.current?.abort(),[]);const exerciseName=(id:string)=>data.exercises.find(e=>e.id===id)?.name||'exercise';const describe=(c:SessionCoachReply['changes'][number])=>c.type==='replace_exercise'?`Replace ${exerciseName(c.exerciseId)} with ${exerciseName(c.replacementExerciseId||'')}`:c.type==='add_exercise'?`Add ${exerciseName(c.exerciseId)}`:c.type==='remove_exercise'?`Remove ${exerciseName(c.exerciseId)}`:c.type==='rename_workout'?`Rename workout to “${c.name}”`:`Adjust ${exerciseName(c.exerciseId)}${c.sets?` to ${c.sets} sets`:''}${c.reps?` × ${c.reps} reps`:''}${c.weight!==null?` at ${c.weight} lb`:''}`;
async function send(){if(busy||!input.trim())return;const next=[...messages.slice(-10),{role:'user' as const,content:input.trim()}];setBusy(true);setError('');setProposal(null);controller.current=new AbortController();try{const response=await fetch('/api/session-coach',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({messages:next,workout,exercises:data.exercises.map(({id,name,category})=>({id,name,category}))}),signal:controller.current.signal});const body=await response.json();if(!response.ok)throw new Error(body.error||'Your coach could not respond.');const reply=sessionCoachSchema.parse(body);setMessages([...next,{role:'assistant',content:reply.message}]);setProposal(reply.changes.length?reply:null);setInput('')}catch(e){setError(e instanceof Error?e.message:'Your coach could not respond.')}finally{setBusy(false)}}
function apply(){if(!proposal)return;let next=workout;for(const c of proposal.changes){if(c.type==='rename_workout'&&c.name)next={...next,name:c.name};if(c.type==='remove_exercise')next={...next,entries:next.entries.filter(e=>e.exerciseId!==c.exerciseId||e.sets.some(s=>s.status!=='pending'))};if(c.type==='replace_exercise'&&c.replacementExerciseId)next={...next,entries:next.entries.map(e=>e.exerciseId===c.exerciseId&&e.sets.every(s=>s.status==='pending')?{exerciseId:c.replacementExerciseId!,sets:Array.from({length:c.sets||e.sets.length||3},()=>setOf(c.weight??e.sets[0]?.weight??0,c.reps??e.sets[0]?.reps??8))}:e)};if(c.type==='adjust_exercise')next={...next,entries:next.entries.map(e=>e.exerciseId===c.exerciseId&&e.sets.every(s=>s.status==='pending')?{...e,sets:Array.from({length:c.sets||e.sets.length||3},()=>setOf(c.weight??e.sets[0]?.weight??0,c.reps??e.sets[0]?.reps??8))}:e)};if(c.type==='add_exercise'&&!next.entries.some(e=>e.exerciseId===c.exerciseId))next={...next,entries:[...next.entries,{exerciseId:c.exerciseId,sets:Array.from({length:c.sets||3},()=>setOf(c.weight??0,c.reps??8))}]}}onApply(next);setProposal(null);setMessages(m=>[...m,{role:'assistant',content:'Done — I updated this session.'}])}
return <section className="panel session-coach"><div className="section-head"><div><h2><Sparkles size={20}/> Ask your session coach</h2><p>Swap an exercise, adjust today’s workout, or ask how to perform a movement.</p></div><AIConnection/></div>{messages.length>0&&<div className="session-coach-messages" role="log">{messages.map((m,i)=><div key={i} className={'plan-message '+m.role}><strong>{m.role==='user'?'You':'Stride'}</strong><p>{m.content}</p></div>)}</div>}{proposal&&<div className="session-proposal"><strong>Proposed changes</strong>{proposal.changes.map((c,i)=><span key={i}><Check size={15}/>{describe(c)}</span>)}<div><button className="primary" onClick={apply}><Check size={17}/> Apply changes</button><button className="secondary" onClick={()=>setProposal(null)}><X size={17}/> Keep workout</button></div></div>}<form onSubmit={e=>{e.preventDefault();void send()}}><label htmlFor="session-question">What do you need?</label><textarea id="session-question" rows={2} maxLength={4000} value={input} disabled={busy} onChange={e=>setInput(e.target.value)} placeholder="I don’t have heavier dumbbells. Can we swap this exercise?"/><button className="primary" disabled={busy||!input.trim()}>{busy?<Loader2 className="plan-spin" size={18}/>:<Send size={18}/>} {busy?'Thinking…':'Ask coach'}</button>{error&&<p className="plan-error" role="alert">{error}</p>}</form></section>}
