'use client';
import {useEffect,useRef,useState} from 'react';
import {Sparkles,Send,Loader2,Check,X} from 'lucide-react';
import {CoachLauncher} from './coach-launcher';
import {CoachConversation} from './coach-conversation';
import {AIConnection} from '@/components/ai-connection';
import {Data,Workout} from '@/lib/training';
import {applySessionChanges} from '@/lib/apply-session-changes';
import {SessionCoachReply,sessionCoachSchema} from '@/lib/session-coach';
import {coachingContext} from '@/lib/adaptive-coach';
import {goalProgress} from '@/lib/goals';
import {useCoachMemory} from '@/components/coach-memory';
import {CoachSaveOffer} from '@/components/coach-save-offer';
type ChatMessage={role:'user'|'assistant';content:string};
export function SessionCoach({data,workout}:{data:Data;workout:Workout}){const {messages:storedMessages,setMessages,setOffer,applyNow}=useCoachMemory('session:'+workout.id);const messages=storedMessages.length?storedMessages:workout.coachMessages||[];const [open,setOpen]=useState(false);const [input,setInput]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[proposal,setProposal]=useState<SessionCoachReply|null>(null);const latest=useRef(workout);latest.current=workout;const proposalSnapshot=useRef('');const controller=useRef<AbortController|null>(null);useEffect(()=>{controller.current?.abort();setProposal(null);setError('')},[workout.id]);useEffect(()=>()=>controller.current?.abort(),[]);const exerciseName=(id:string)=>data.exercises.find(e=>e.id===id)?.name||'exercise';const describe=(c:SessionCoachReply['changes'][number])=>c.type==='replace_exercise'?`Replace ${exerciseName(c.exerciseId)} with ${exerciseName(c.replacementExerciseId||'')}`:c.type==='add_exercise'?`Add ${exerciseName(c.exerciseId)}`:c.type==='remove_exercise'?`Remove ${exerciseName(c.exerciseId)}`:c.type==='rename_workout'?`Rename workout to “${c.name}”`:`Adjust ${exerciseName(c.exerciseId)}${c.sets?` to ${c.sets} sets`:''}${c.reps?` × ${c.reps} reps`:''}${c.weight!==null?` at ${c.weight} lb`:''}`;
async function send(prompt=input){if(busy||!prompt.trim())return;const next=[...messages.slice(-10),{role:'user' as const,content:prompt.trim()}];setBusy(true);setError('');setProposal(null);controller.current=new AbortController();try{const response=await fetch('/api/session-coach',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({messages:next,workout,context:JSON.stringify({...coachingContext(data),goalProgress:(data.goals||[]).filter(g=>!g.archived).map(g=>({title:g.title,...goalProgress(g,data)}))}).slice(0,100000),exercises:data.exercises.map(({id,name,category})=>({id,name,category}))}),signal:controller.current.signal});const body=await response.json() as SessionCoachReply & {error?:string};if(!response.ok)throw new Error(body.error||'Your coach could not respond.');if(latest.current.id!==workout.id)return;const reply=sessionCoachSchema.parse(body);proposalSnapshot.current=JSON.stringify(workout.entries);const conversation=[...messages,next[next.length-1],{role:'assistant' as const,content:reply.message}].slice(-200);setMessages(conversation);if(reply.changes.length){const result=applySessionChanges(latest.current,reply.changes,data.exercises.map(e=>e.id));if(result.skipped)throw new Error('Some suggested changes are no longer valid. Ask your coach to review the remaining sets.');if(result.applied)setProposal(reply);}setOffer(reply.saveUpdates||null);setInput('')}catch(e){setError(e instanceof Error?e.message:'Your coach could not respond.')}finally{setBusy(false)}}
if(!open)return <CoachLauncher hint="Get advice or adjust this workout." hasMessages={messages.length>0} onOpen={()=>setOpen(true)}/>;
return <section className="panel session-coach"><div className="section-head"><div><h2><Sparkles size={20}/> Your coach</h2><p>Ask a question, get guidance, or adjust this workout.</p></div><div className="plan-header-actions"><AIConnection/><button className="icon-button" aria-label="Close coach" disabled={busy} onClick={()=>setOpen(false)}><X size={18}/></button></div></div>{!messages.length&&<div className="coach-prompts">{["How should I approach today’s workout?","Review my sets and suggest adjustments","How is this helping my goals?"].map(prompt=><button className="secondary" disabled={busy} key={prompt} onClick={()=>void send(prompt)}>{prompt}</button>)}</div>}<CoachConversation messages={messages}/>{proposal&&<div className="session-proposal"><h3>Proposed workout changes</h3><ul>{proposal.changes.map((c,i)=><li key={i}>{describe(c)}</li>)}</ul><button className="primary" disabled={busy} onClick={async()=>{setBusy(true);try{if(JSON.stringify(latest.current.entries)!==proposalSnapshot.current)throw new Error('Your sets changed. Ask the coach to review the latest workout.');const result=applySessionChanges(latest.current,proposal.changes,data.exercises.map(e=>e.id));if(result.skipped)throw new Error('Some changes are no longer valid. Ask the coach again.');if(await applyNow('session',{...data,workouts:data.workouts.map(w=>w.id===result.workout.id?result.workout:w)},'Update workout · '+result.workout.name)){setProposal(null);setMessages(old=>[...old,{role:'assistant',content:'Workout changes saved. Your conversation is still here.'}])}else setError('Changes were not saved. Please retry.')}catch(e){setError((e as Error).message)}finally{setBusy(false)}}}>Approve and save</button><button className="text-button" disabled={busy} onClick={()=>setProposal(null)}>Discard</button></div>}<CoachSaveOffer area={'session:'+workout.id}/><form onSubmit={e=>{e.preventDefault();void send()}}><label htmlFor="session-question">Reply to your coach</label><textarea id="session-question" rows={2} maxLength={4000} value={input} disabled={busy} onChange={e=>setInput(e.target.value)} placeholder="I don’t have heavier dumbbells. Can we swap this exercise?"/><button className="primary" disabled={busy||!input.trim()}>{busy?<Loader2 className="plan-spin" size={18}/>:<Send size={18}/>} {busy?'Thinking…':'Ask coach'}</button>{error&&<p className="plan-error" role="alert">{error}</p>}</form></section>}
