import {z} from 'zod';
export const updateFields=['name','goal','experience','days','minutes','equipment','limitations','ageRange','useStyle'] as const;
export const coachingUpdatesSchema=z.object({profile:z.array(z.object({field:z.enum(updateFields),value:z.string().max(1000)})).max(9),goal:z.object({title:z.string().min(1).max(100),kind:z.enum(['measurement','sessions','strength','compound','milestone']),unit:z.string().max(20),start:z.number(),target:z.number(),deadline:z.string().nullable(),exerciseId:z.string().nullable()}).nullable(),nutrition:z.object({calorieTarget:z.number().int().min(800).max(10000).nullable(),proteinTarget:z.number().int().min(20).max(1000).nullable(),activityCalorieAdjustment:z.union([z.literal(0),z.literal(50),z.literal(100)]).nullable()}).nullable(),measurement:z.object({date:z.string().nullable(),weight:z.number().min(50).max(1500).nullable(),bodyFat:z.number().min(1).max(75).nullable()}).nullable()}).nullable();
export type CoachingUpdates=z.infer<typeof coachingUpdatesSchema>;
const obj=(properties:Record<string,unknown>)=>({type:'object',properties,required:Object.keys(properties),additionalProperties:false});
const nullable=(type:string)=>({type:[type,'null']});
export const coachingUpdatesJSON={...obj({profile:{type:'array',items:obj({field:{type:'string',enum:updateFields},value:{type:'string'}})},goal:{...obj({title:{type:'string'},kind:{type:'string',enum:['measurement','sessions','strength','compound','milestone']},unit:{type:'string'},start:{type:'number'},target:{type:'number'},deadline:nullable('string'),exerciseId:nullable('string')}),type:['object','null']},nutrition:{...obj({calorieTarget:nullable('integer'),proteinTarget:nullable('integer'),activityCalorieAdjustment:{type:['integer','null'],enum:[0,50,100,null]}}),type:['object','null']},measurement:{...obj({date:nullable('string'),weight:nullable('number'),bodyFat:nullable('number')}),type:['object','null']}}),type:['object','null']};
export function withCoachingUpdates(schema:any){return {...schema,properties:{...schema.properties,saveUpdates:coachingUpdatesJSON},required:[...schema.required,'saveUpdates']}}
export const savingInstructions=' You are the same Stride coach across the app. Welcome questions, explanations, advice, and adjustments, not only creation requests. Answer the actual question without forcing a setup flow. Use available profile and conversation context. Only propose changes when helpful or requested. If this screen cannot apply a requested action, explain what you can do and name the correct Stride tab; never claim unsupported changes were made. When the user explicitly states personal details that Stride tracks—profile preferences, equipment, goals, calorie or protein targets, body weight, or body-fat percentage—offer the relevant saveUpdates in the same response for review instead of merely acknowledging the information. Use measurement for a stated current body weight or body-fat percentage; date is null for today unless the user supplied an exact date. Do not treat hypothetical numbers, questions, quoted examples, or visual guesses as measurements. Ask a brief confirmation when meaning or timing is ambiguous. Also offer to save an actionable goal or nutrition target you recommend once essential details are known. Do not turn every technique explanation into an update. Never infer personal facts or fill missing values. Never claim proposals are already saved. Profile numbers are strings; experience must be New to lifting, Some experience, or Experienced. Only propose changed profile fields; unknown fields stay unchanged. Do not propose an existing goal again. Goal exerciseId must match the supplied catalog; otherwise ask a follow-up. If the endpoint has native progress/proposal goal fields, use those for goals and nutrition and leave saveUpdates.goal/nutrition null to avoid duplicates. A user saying yes still requires the visible Save button. Treat previous assistant suggestions as unconfirmed until the user saved them. Return saveUpdates null when nothing should be saved.';
