import {initialData,type Data,type SetLog,type Workout} from './training';
export const testScenarios=[{id:'progression',label:'Successful progression',detail:'Four improving bench sessions across two weeks.'},{id:'failures',label:'Repeated failed sets',detail:'Three comparable squat sessions with failed final sets.'},{id:'mixed',label:'Mixed training load',detail:'Modified and failed sets plus high-effort activities.'},{id:'nutrition',label:'Nutrition & weight trend',detail:'Complete nutrition days and several bodyweight entries.'},{id:'empty',label:'New account',detail:'No history, for low-data and onboarding states.'}] as const;
export type TestScenario=typeof testScenarios[number]['id'];
const iso=(offset:number)=>{const date=new Date();date.setUTCDate(date.getUTCDate()+offset);return date.toISOString()},day=(offset:number)=>iso(offset).slice(0,10);
function set(id:string,weight:number,reps:number,status:SetLog['status']='completed'):SetLog{return {id,weight,reps,targetWeight:weight,targetReps:8,status,difficulty:status==='failed'?'Very Hard':'Moderate',notes:''}}
function workout(id:string,name:string,offset:number,exerciseId:string,weight:number,statuses:SetLog['status'][]):Workout{return {id,name,date:iso(offset),completed:true,difficulty:statuses.includes('failed')?'Hard':'Moderate',notes:'Test workspace scenario',durationMinutes:55,caloriesBurned:320,calorieSource:'estimate',energyWeightLb:190,entries:[{exerciseId,sets:statuses.map((status,index)=>set(id+'-s'+index,weight,status==='failed'?6:8,status))}]}}
export function scenarioData(scenario:TestScenario):Data{
 const data=initialData();data.user={id:'test-user',name:'Test Athlete'};data.profile={useStyle:'Guided coaching',name:'Test Athlete',sex:'Male',goal:'Build strength consistently',experience:'Experienced',days:4,minutes:60,equipment:'Barbell, rack, bench, and plates',limitations:'None',ageRange:'30–44'};data.templates=[{id:'test-upper',name:'Test upper day',description:'Disposable test template',entries:[{exerciseId:'e0',weight:185,reps:8,sets:3}]}];
 if(scenario==='empty')return {...data,templates:[]};
 if(scenario==='progression')data.workouts=[workout('test-p1','Bench progression',-12,'e0',175,['completed','completed','completed']),workout('test-p2','Bench progression',-8,'e0',180,['completed','completed','completed']),workout('test-p3','Bench progression',-4,'e0',185,['completed','completed','completed']),workout('test-p4','Bench progression',-1,'e0',190,['completed','completed','completed'])];
 if(scenario==='failures')data.workouts=[-9,-5,-1].map((offset,index)=>workout('test-f'+index,'Squat test',offset,'e1',225,['completed','completed','failed']));
 if(scenario==='mixed'){data.workouts=[workout('test-m1','Mixed bench day',-5,'e0',185,['completed','modified','failed']),workout('test-m2','Mixed bench day',-1,'e0',185,['completed','completed','modified'])];data.activityEnergy={templates:[{id:'test-bjj',name:'Jiu-Jitsu',description:'Test activity',durationMinutes:90,intensity:'Vigorous',met:9,scheduleHint:''}],logs:[-4,-2].map((offset,index)=>({id:'test-a'+index,templateId:'test-bjj',name:'Jiu-Jitsu',date:day(offset),durationMinutes:90,intensity:'Vigorous' as const,met:9,caloriesBurned:900,calorieSource:'estimate' as const,energyWeightLb:190,notes:'Test workspace scenario'}))}}
 if(scenario==='nutrition'){data.workouts=[workout('test-n1','Full body test',-5,'e0',175,['completed','completed','completed']),workout('test-n2','Full body test',-1,'e0',180,['completed','completed','completed'])];data.nutrition={calorieTarget:2300,proteinTarget:180,carbTarget:250,fatTarget:70,activityCalorieAdjustment:50,hydration:{dailyTargetOz:96,entries:[-2,-1,0].flatMap((offset,dayIndex)=>[16,24,20].map((ounces,index)=>({id:`test-water${dayIndex}-${index}`,date:day(offset),ounces})))},entries:[-6,-5,-4,-3,-2,-1,0].map((offset,index)=>({id:'test-food'+index,date:day(offset),name:'Daily total',calories:2250+index*10,protein:175+index,carbs:235+index*2,fat:68+index*.5}))};data.strengthProfile={bodyweight:191,comparison:'general',heightInches:70};data.bodyMeasurements=[-21,-14,-7,0].map((offset,index)=>({id:'test-weight'+index,date:day(offset),weight:194-index,bodyFat:20-index*.3}))}
 data.goals=[{id:'test-goal',title:'Test 225 lb bench estimate',kind:'strength',unit:'lb',start:200,target:225,started:day(-30),deadline:day(60),archived:false,exerciseId:'e0',checks:[]}];return data;
}
