import {initialData,type Data,type Exercise,type SetLog,type Workout} from './training';
import {muscleGroups} from './muscle-recovery';
const recoveryScenarios=[{id:'recovery-male-all',label:'Male map · all recovering',detail:'Highlights every recovery region together on the male figure.'},{id:'recovery-male-mixed',label:'Male map · mixed recovery',detail:'Shows recovering, nearly recovered, and likely ready muscles. Advance the test day to watch them progress.'},{id:'recovery-female-all',label:'Female map · all recovering',detail:'Highlights every recovery region together on the female figure.'},{id:'recovery-female-mixed',label:'Female map · mixed recovery',detail:'Shows recovering, nearly recovered, and likely ready muscles. Advance the test day to watch them progress.'}] as const;
export const testScenarios=[{id:'hypertrophy',label:'Upper/lower hypertrophy · two weeks',detail:'Four-day evidence-informed plan with eight logged workouts and varied progression evidence.'},{id:'equipment-limited',label:'Progression · equipment limit',detail:'A small cable stack jump should keep load steady and progress reps.'},{id:'scope-comparison',label:'Progression · grouped vs independent',detail:'Compare one grouped prescription with independently progressing sets.'},{id:'long-gap',label:'Progression · long layoff',detail:'Recent training resumes after a long gap; old success should not confirm a jump.'},{id:'manual-target',label:'Progression · manual target',detail:'A saved manual target should remain in control of the recommendation.'},{id:'insufficient-history',label:'Progression · one logged session',detail:'A single recent workout should not imply confirmed progression.'},{id:'progression',label:'Successful progression',detail:'Four improving bench sessions across two weeks.'},{id:'failures',label:'Repeated failed sets',detail:'Three comparable squat sessions with failed final sets.'},{id:'mixed',label:'Mixed training load',detail:'Modified and failed sets plus high-effort activities.'},{id:'nutrition',label:'Nutrition & weight trend',detail:'Complete nutrition days and several bodyweight entries.'},{id:'empty',label:'New account',detail:'No history, for low-data and onboarding states.'},...recoveryScenarios] as const;
export type TestScenario=typeof testScenarios[number]['id'];
const iso=(offset:number)=>{const date=new Date();date.setUTCDate(date.getUTCDate()+offset);return date.toISOString()},day=(offset:number)=>iso(offset).slice(0,10);
const hoursAgo=(hours:number)=>new Date(Date.now()-hours*36e5).toISOString();
function set(id:string,weight:number,reps:number,status:SetLog['status']='completed'):SetLog{return {id,weight,reps,targetWeight:weight,targetReps:8,status,difficulty:status==='failed'?'Very Hard':'Moderate',notes:''}}
function workout(id:string,name:string,offset:number,exerciseId:string,weight:number,statuses:SetLog['status'][]):Workout{return {id,name,date:iso(offset),completed:true,difficulty:statuses.includes('failed')?'Hard':'Moderate',notes:'Test workspace scenario',durationMinutes:55,caloriesBurned:320,calorieSource:'estimate',energyWeightLb:190,entries:[{exerciseId,sets:statuses.map((status,index)=>set(id+'-s'+index,weight,status==='failed'?6:8,status))}]}}
const repPolicy:import('./training').ProgressionPolicy={kind:'rep_range',scope:'group',advanceBy:'auto',successSessions:2,failureAction:'hold'};
const exercise=(id:string,name:string,category:string,weight:number,model:Exercise['loadAvailability']={kind:'increment',step:5},increment=5):Exercise=>({id,name,category,increment,loadAvailability:model,mode:'weight',baseWeight:weight,baseReps:8,baseSets:3});
const prescription=(id:string,weight:number,minReps:number,maxReps:number,role:NonNullable<SetLog['prescription']>['role']='working'):NonNullable<SetLog['prescription']>=>({id,role,countsTowardProgression:role!=='warmup'&&role!=='ramp',targetWeight:weight,minReps,maxReps,targetRir:2,group:id});
const hypertrophyExercises:Exercise[]=[
 exercise('hy-bench','Barbell bench press','Chest',155),exercise('hy-row','Chest-supported row','Back',90),exercise('hy-incline','Incline dumbbell press','Chest',45,{kind:'discrete',values:[20,25,30,35,40,45,50,55,60]}),exercise('hy-pulldown','Lat pulldown','Back',110),exercise('hy-lateral','Cable lateral raise','Shoulders',15,{kind:'discrete',values:[5,7.5,10,12.5,15,17.5,20],maxJump:2.5}),exercise('hy-pushdown','Cable triceps pressdown','Arms',45),
 exercise('hy-squat','Barbell back squat','Legs',185),exercise('hy-rdl','Romanian deadlift','Legs',155),exercise('hy-leg-press','Leg press','Legs',270,{kind:'increment',step:10},10),exercise('hy-leg-curl','Seated leg curl','Legs',80),exercise('hy-calf','Standing calf raise','Legs',100),
 exercise('hy-ohp','Seated dumbbell shoulder press','Shoulders',35,{kind:'discrete',values:[15,20,25,30,35,40,45,50]}),exercise('hy-pullup','Assisted pull-up','Back',40,{kind:'increment',step:5}),exercise('hy-machine-press','Machine chest press','Chest',100,{kind:'increment',step:5}),exercise('hy-cable-row','Seated cable row','Back',100),exercise('hy-rear-delt','Reverse pec deck','Shoulders',70),exercise('hy-curl','Dumbbell curl','Arms',25,{kind:'discrete',values:[10,12.5,15,17.5,20,22.5,25,27.5,30]}),
 exercise('hy-hip-thrust','Barbell hip thrust','Legs',185),exercise('hy-split-squat','Bulgarian split squat','Legs',30,{kind:'discrete',values:[10,15,20,25,30,35,40,45]}),exercise('hy-lying-curl','Lying leg curl','Legs',75),exercise('hy-seated-calf','Seated calf raise','Legs',90),
];
const hypertrophyPlan=[
 {id:'hy-upper-a',name:'Upper A · chest and back',description:'Compounds first, then focused shoulder and arm work.',ids:['hy-bench','hy-row','hy-incline','hy-pulldown','hy-lateral','hy-pushdown'],ranges:[[6,10,3],[8,12,3],[8,12,3],[8,12,3],[12,20,3],[10,15,2]]},
 {id:'hy-lower-a',name:'Lower A · squat emphasis',description:'Squat and hinge work with moderate accessory volume.',ids:['hy-squat','hy-rdl','hy-leg-press','hy-leg-curl','hy-calf'],ranges:[[6,10,3],[6,10,3],[10,15,3],[10,15,3],[8,15,3]]},
 {id:'hy-upper-b',name:'Upper B · shoulders and arms',description:'Vertical pressing and pulling with balanced chest and arm work.',ids:['hy-ohp','hy-pullup','hy-machine-press','hy-cable-row','hy-rear-delt','hy-curl'],ranges:[[6,10,3],[6,10,3],[8,12,3],[8,12,3],[12,20,3],[10,15,3]]},
 {id:'hy-lower-b',name:'Lower B · posterior-chain emphasis',description:'Hip extension, unilateral legs, hamstrings, and calves.',ids:['hy-hip-thrust','hy-split-squat','hy-lying-curl','hy-seated-calf'],ranges:[[8,12,3],[8,12,3],[10,15,3],[8,15,3]]},
].map((template,index)=>({...template,revision:1,description:`Four-day upper/lower hypertrophy plan · ${template.description}`,entries:template.ids.map((exerciseId,i)=>{const item=hypertrophyExercises.find(x=>x.id===exerciseId)!;const [min,max,sets]=template.ranges[i];const row=prescription(`${exerciseId}-working`,item.baseWeight,min,max);return {exerciseId,weight:item.baseWeight,reps:min,sets,setPrescriptions:Array.from({length:sets},()=>({...row})),progressionPolicy:{...repPolicy}}})}));
function hypertrophyData(data:Data):Data{
 data.user={id:'test-user',name:'Jordan Lee'};data.profile={useStyle:'Guided coaching',name:'Jordan Lee',sex:'Male',goal:'Build muscle with steady, measurable strength progress',experience:'Experienced',days:4,minutes:60,equipment:'Full gym: barbell, rack, bench, dumbbells, cables, and machines',limitations:'None',ageRange:'30–44'};
 data.exercises=[...data.exercises,...hypertrophyExercises];data.templates=hypertrophyPlan;
 const offsets=[-13,-12,-10,-9,-6,-5,-3,-2],templateOrder=[0,1,2,3,0,1,2,3];
 data.workouts=templateOrder.map((templateIndex,sessionIndex)=>{const template=hypertrophyPlan[templateIndex],week=sessionIndex<4?0:1;return {id:`hy-session-${sessionIndex+1}`,name:template.name,templateId:template.id,date:iso(offsets[sessionIndex]),completed:true,difficulty:'Moderate',notes:week===0?'Week 1: controlled reps, generally 2 reps in reserve.':'Week 2: repeatable technique; compound lifts mostly at the top of the rep range.',durationMinutes:55+template.entries.length*3,caloriesBurned:360,calorieSource:'estimate' as const,energyWeightLb:176,entries:template.entries.map(entry=>({exerciseId:entry.exerciseId,progressionPolicy:{...entry.progressionPolicy},prescriptionVersion:1,prescriptionContext:`${template.id}:1:${entry.exerciseId}`,sets:Array.from({length:entry.sets},(_,setIndex)=>{const row={...entry.setPrescriptions![setIndex]};const start=row.minReps;const reachTop=['hy-bench','hy-squat','hy-row'].includes(entry.exerciseId);const reps=reachTop?10:(week===0?Math.min(row.maxReps,start+Math.min(setIndex,2)):Math.min(row.maxReps,start+Math.min(setIndex+1,3)));return {id:`hy-session-${sessionIndex+1}-${entry.exerciseId}-${setIndex+1}`,weight:row.targetWeight,reps,targetWeight:row.targetWeight,targetReps:row.minReps,status:'completed' as const,difficulty:'Moderate',notes:'Approximately 1–3 reps in reserve; no grinding reps.',actualRir:reachTop&&reps===10?2:3,prescription:row}})}))}});
 data.goals=[{id:'hy-goal',title:'Build muscle while progressing key lifts',kind:'strength',unit:'lb',start:155,target:175,started:day(-14),deadline:day(90),archived:false,exerciseId:'hy-bench',checks:[]}];
 data.strengthProfile={bodyweight:176,comparison:'general',heightInches:70};data.bodyMeasurements=[-14,-7,0].map((offset,index)=>({id:`hy-weight-${index}`,date:day(offset),weight:176+index*.2,bodyFat:null}));
 return data;
}
export function scenarioData(scenario:TestScenario):Data{
 const data=initialData();data.user={id:'test-user',name:'Test Athlete'};data.profile={useStyle:'Guided coaching',name:'Test Athlete',sex:'Male',goal:'Build strength consistently',experience:'Experienced',days:4,minutes:60,equipment:'Barbell, rack, bench, and plates',limitations:'None',ageRange:'30–44'};data.templates=[{id:'test-upper',name:'Test upper day',description:'Disposable test template',entries:[{exerciseId:'e0',weight:185,reps:8,sets:3}]}];
 if(scenario.startsWith('recovery-')){
  const sex=scenario.includes('female')?'Female':'Male',mixed=scenario.includes('mixed'),exercises:Exercise[]=muscleGroups.map((group,index)=>({id:`test-recovery-${index}`,name:`${group} isolation test`,category:group,increment:5,mode:'weight',baseWeight:50,baseReps:8,baseSets:3}));
  data.profile={...data.profile,sex};data.exercises=[...data.exercises,...exercises];data.templates=[];
  data.workouts=mixed?exercises.map((exercise,index)=>({id:`test-recovery-workout-${index}`,name:`${exercise.category} recovery timing test`,date:hoursAgo([12,30,72][index%3]),completed:true,difficulty:'Moderate',notes:'Advance the test date to watch this recovery state change.',durationMinutes:10,entries:[{exerciseId:exercise.id,sets:[set(`test-recovery-${index}-set`,50,8)]}]})):[{id:'test-recovery-workout',name:'All muscle recovery map test',date:iso(-1),completed:true,difficulty:'Moderate',notes:'Visual QA fixture for every muscle region',durationMinutes:55,entries:exercises.map((exercise,index)=>({exerciseId:exercise.id,sets:[set(`test-recovery-${index}-set`,50,8)]}))}];
  return data;
 }
 if(scenario==='hypertrophy')return hypertrophyData(data);
 if(scenario==='equipment-limited'){
  const e=exercise('test-cable-lateral','Cable lateral raise','Shoulders',15,{kind:'discrete',values:[5,7.5,10,12.5,15],maxJump:2.5});data.exercises=[...data.exercises,e];const row=prescription('lateral',15,12,15),entry={exerciseId:e.id,weight:15,reps:12,sets:3,setPrescriptions:Array.from({length:3},()=>({...row})),progressionPolicy:{...repPolicy,advanceBy:'load' as const}};data.templates=[{id:'equipment-template',revision:1,name:'Small-stack equipment test',description:'Progression test for a jump that exceeds the configured limit.',entries:[entry]}];data.workouts=[-7,-1].map((offset,index)=>({id:`equipment-${index}`,name:'Cable lateral raise test',templateId:'equipment-template',date:iso(offset),completed:true,difficulty:'Moderate',notes:'All working sets reached the top of the prescribed range.',entries:[{exerciseId:e.id,progressionPolicy:{...repPolicy,advanceBy:'load'},prescriptionVersion:1,prescriptionContext:`equipment-template:1:${e.id}`,sets:Array.from({length:3},(_,i)=>({id:`equipment-${index}-${i}`,weight:15,reps:15,targetWeight:15,targetReps:12,status:'completed' as const,difficulty:'Moderate',notes:'',prescription:{...row}}))}]}));return data;
 }
 if(scenario==='scope-comparison'){
  const grouped=exercise('test-grouped','Grouped bench test','Chest',100),independent=exercise('test-independent','Independent bench test','Chest',80);data.exercises=[...data.exercises,grouped,independent];const groupedRow=prescription('grouped',100,8,10),independentRows=Array.from({length:3},(_,i)=>prescription(`independent-${i}`,80,8,10));const template={id:'scope-template',revision:1,name:'Grouped vs independent',description:'Same recent history shape; compare progression scopes.',entries:[{exerciseId:grouped.id,weight:100,reps:8,sets:3,setPrescriptions:Array.from({length:3},()=>({...groupedRow})),progressionPolicy:{...repPolicy,scope:'group' as const}},{exerciseId:independent.id,weight:80,reps:8,sets:3,setPrescriptions:independentRows,progressionPolicy:{...repPolicy,scope:'independent' as const}}]};data.templates=[template];data.workouts=[-7,-1].map((offset,index)=>({id:`scope-${index}`,name:'Grouped vs independent',templateId:template.id,date:iso(offset),completed:true,difficulty:'Moderate',notes:'Grouped rows have mixed performance; independent row 1 reaches the top twice.',entries:[{exerciseId:grouped.id,progressionPolicy:{...repPolicy,scope:'group'},prescriptionVersion:1,prescriptionContext:`${template.id}:1:${grouped.id}`,sets:Array.from({length:3},(_,i)=>({id:`scope-g-${index}-${i}`,weight:100,reps:i===0?10:8+index,targetWeight:100,targetReps:8,status:'completed' as const,difficulty:'Moderate',notes:'',prescription:{...groupedRow}}))},{exerciseId:independent.id,progressionPolicy:{...repPolicy,scope:'independent'},prescriptionVersion:1,prescriptionContext:`${template.id}:1:${independent.id}`,sets:independentRows.map((row,i)=>({id:`scope-i-${index}-${i}`,weight:80,reps:i===0?10:8+index,targetWeight:80,targetReps:8,status:'completed' as const,difficulty:'Moderate',notes:'',prescription:{...row}}))}]}));return data;
 }
 if(scenario==='long-gap'||scenario==='insufficient-history'||scenario==='manual-target'){
  const e=exercise('test-gap-bench','Test bench press','Chest',100),row=prescription('main',100,8,10),template={id:'history-template',revision:1,name:'History confidence test',description:'Check confidence and manual target handling.',entries:[{exerciseId:e.id,weight:100,reps:8,sets:2,setPrescriptions:[{...row},{...row}],progressionPolicy:{...repPolicy}}]};data.exercises=[...data.exercises,e];data.templates=[template];const offsets=scenario==='long-gap'?[-70,-1]:scenario==='manual-target'?[-7,-1]:[-1];data.workouts=offsets.map((offset,index)=>({id:`history-${index}`,name:'Test bench press',templateId:template.id,date:iso(offset),completed:true,difficulty:'Moderate',notes:'Top of range on each working set.',entries:[{exerciseId:e.id,progressionPolicy:{...repPolicy},prescriptionVersion:1,prescriptionContext:`${template.id}:1:${e.id}`,sets:[0,1].map(i=>({id:`history-${index}-${i}`,weight:100,reps:10,targetWeight:100,targetReps:8,status:'completed' as const,difficulty:'Moderate',notes:'',prescription:{...row}}))}]}));if(scenario==='manual-target')data.overrides[e.id]={weight:92.5,reps:8,sets:2};return data;
 }
 if(scenario==='empty')return {...data,profile:undefined,templates:[]};
 if(scenario==='progression')data.workouts=[workout('test-p1','Bench progression',-12,'e0',175,['completed','completed','completed']),workout('test-p2','Bench progression',-8,'e0',180,['completed','completed','completed']),workout('test-p3','Bench progression',-4,'e0',185,['completed','completed','completed']),workout('test-p4','Bench progression',-1,'e0',190,['completed','completed','completed'])];
 if(scenario==='failures')data.workouts=[-9,-5,-1].map((offset,index)=>workout('test-f'+index,'Squat test',offset,'e1',225,['completed','completed','failed']));
 if(scenario==='mixed'){data.workouts=[workout('test-m1','Mixed bench day',-5,'e0',185,['completed','modified','failed']),workout('test-m2','Mixed bench day',-1,'e0',185,['completed','completed','modified'])];data.activityEnergy={templates:[{id:'test-bjj',name:'Jiu-Jitsu',description:'Test activity',durationMinutes:90,intensity:'Vigorous',met:9,scheduleHint:''}],logs:[-4,-2].map((offset,index)=>({id:'test-a'+index,templateId:'test-bjj',name:'Jiu-Jitsu',date:day(offset),durationMinutes:90,intensity:'Vigorous' as const,met:9,caloriesBurned:900,calorieSource:'estimate' as const,energyWeightLb:190,notes:'Test workspace scenario'}))}}
 if(scenario==='nutrition'){data.workouts=[workout('test-n1','Full body test',-5,'e0',175,['completed','completed','completed']),workout('test-n2','Full body test',-1,'e0',180,['completed','completed','completed'])];data.nutrition={calorieTarget:2300,proteinTarget:180,carbTarget:250,fatTarget:70,activityCalorieAdjustment:50,hydration:{dailyTargetOz:96,entries:[-2,-1,0].flatMap((offset,dayIndex)=>[16,24,20].map((ounces,index)=>({id:`test-water${dayIndex}-${index}`,date:day(offset),ounces})))},entries:[-6,-5,-4,-3,-2,-1,0].map((offset,index)=>({id:'test-food'+index,date:day(offset),name:'Daily total',calories:2250+index*10,protein:175+index,carbs:235+index*2,fat:68+index*.5}))};data.strengthProfile={bodyweight:191,comparison:'general',heightInches:70};data.bodyMeasurements=[-21,-14,-7,0].map((offset,index)=>({id:'test-weight'+index,date:day(offset),weight:194-index,bodyFat:20-index*.3}))}
 data.goals=[{id:'test-goal',title:'Test 225 lb bench estimate',kind:'strength',unit:'lb',start:200,target:225,started:day(-30),deadline:day(60),archived:false,exerciseId:'e0',checks:[]}];return data;
}
